# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2024, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# Rafael Fontenelle <rffontenelle@gmail.com>, 2024
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.12\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-08-31 11:30+0000\n"
"PO-Revision-Date: 2024-05-11 00:33+0000\n"
"Last-Translator: Rafael Fontenelle <rffontenelle@gmail.com>, 2024\n"
"Language-Team: Portuguese (Brazil) (https://app.transifex.com/python-doc/"
"teams/5390/pt_BR/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt_BR\n"
"Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % "
"1000000 == 0 ? 1 : 2;\n"

#: ../../library/asyncio-task.rst:6
msgid "Coroutines and Tasks"
msgstr "Corrotinas e Tarefas"

#: ../../library/asyncio-task.rst:8
msgid ""
"This section outlines high-level asyncio APIs to work with coroutines and "
"Tasks."
msgstr ""
"Esta seção descreve APIs assíncronas de alto nível para trabalhar com "
"corrotinas e tarefas."

#: ../../library/asyncio-task.rst:19 ../../library/asyncio-task.rst:148
msgid "Coroutines"
msgstr "Corrotinas"

#: ../../library/asyncio-task.rst:21
msgid "**Source code:** :source:`Lib/asyncio/coroutines.py`"
msgstr ""

#: ../../library/asyncio-task.rst:25
msgid ""
":term:`Coroutines <coroutine>` declared with the async/await syntax is the "
"preferred way of writing asyncio applications.  For example, the following "
"snippet of code prints \"hello\", waits 1 second, and then prints \"world\"::"
msgstr ""
":term:`Corrotinas <coroutine>` declaradas com a sintaxe async/await é a "
"forma preferida de escrever aplicações assíncronas. Por exemplo, o seguinte "
"trecho de código imprime \"hello\", espera 1 segundo, e então imprime "
"\"world\"::"

#: ../../library/asyncio-task.rst:30
msgid ""
">>> import asyncio\n"
"\n"
">>> async def main():\n"
"...     print('hello')\n"
"...     await asyncio.sleep(1)\n"
"...     print('world')\n"
"\n"
">>> asyncio.run(main())\n"
"hello\n"
"world"
msgstr ""

#: ../../library/asyncio-task.rst:41
msgid ""
"Note that simply calling a coroutine will not schedule it to be executed::"
msgstr ""
"Perceba que simplesmente chamar uma corrotina não irá agendá-la para ser "
"executada::"

#: ../../library/asyncio-task.rst:44
msgid ""
">>> main()\n"
"<coroutine object main at 0x1053bb7c8>"
msgstr ""

#: ../../library/asyncio-task.rst:47
msgid "To actually run a coroutine, asyncio provides the following mechanisms:"
msgstr ""

#: ../../library/asyncio-task.rst:49
msgid ""
"The :func:`asyncio.run` function to run the top-level entry point \"main()\" "
"function (see the above example.)"
msgstr ""
"A função :func:`asyncio.run` para executar a função \"main()\" do ponto de "
"entrada no nível mais alto (veja o exemplo acima.)"

#: ../../library/asyncio-task.rst:52
msgid ""
"Awaiting on a coroutine.  The following snippet of code will print \"hello\" "
"after waiting for 1 second, and then print \"world\" after waiting for "
"*another* 2 seconds::"
msgstr ""
"Aguardando uma corrotina. O seguinte trecho de código exibirá \"hello\" após "
"esperar por 1 segundo e, em seguida, exibirá \"world\" após esperar por "
"*outros* 2 segundos::"

#: ../../library/asyncio-task.rst:56
msgid ""
"import asyncio\n"
"import time\n"
"\n"
"async def say_after(delay, what):\n"
"    await asyncio.sleep(delay)\n"
"    print(what)\n"
"\n"
"async def main():\n"
"    print(f\"started at {time.strftime('%X')}\")\n"
"\n"
"    await say_after(1, 'hello')\n"
"    await say_after(2, 'world')\n"
"\n"
"    print(f\"finished at {time.strftime('%X')}\")\n"
"\n"
"asyncio.run(main())"
msgstr ""

#: ../../library/asyncio-task.rst:73
msgid "Expected output::"
msgstr "Resultado esperado::"

#: ../../library/asyncio-task.rst:75
msgid ""
"started at 17:13:52\n"
"hello\n"
"world\n"
"finished at 17:13:55"
msgstr ""

#: ../../library/asyncio-task.rst:80
msgid ""
"The :func:`asyncio.create_task` function to run coroutines concurrently as "
"asyncio :class:`Tasks <Task>`."
msgstr ""
"A função :func:`asyncio.create_task` para executar corrotinas "
"concorrentemente como :class:`Tasks <Task>` asyncio."

#: ../../library/asyncio-task.rst:83
msgid ""
"Let's modify the above example and run two ``say_after`` coroutines "
"*concurrently*::"
msgstr ""
"Vamos modificar o exemplo acima e executar duas corrotinas ``say_after`` "
"*concorrentemente*::"

#: ../../library/asyncio-task.rst:86
msgid ""
"async def main():\n"
"    task1 = asyncio.create_task(\n"
"        say_after(1, 'hello'))\n"
"\n"
"    task2 = asyncio.create_task(\n"
"        say_after(2, 'world'))\n"
"\n"
"    print(f\"started at {time.strftime('%X')}\")\n"
"\n"
"    # Wait until both tasks are completed (should take\n"
"    # around 2 seconds.)\n"
"    await task1\n"
"    await task2\n"
"\n"
"    print(f\"finished at {time.strftime('%X')}\")"
msgstr ""

#: ../../library/asyncio-task.rst:102
msgid ""
"Note that expected output now shows that the snippet runs 1 second faster "
"than before::"
msgstr ""
"Perceba que a saída esperada agora mostra que o trecho de código é executado "
"1 segundo mais rápido do que antes::"

#: ../../library/asyncio-task.rst:105
msgid ""
"started at 17:14:32\n"
"hello\n"
"world\n"
"finished at 17:14:34"
msgstr ""

#: ../../library/asyncio-task.rst:110
msgid ""
"The :class:`asyncio.TaskGroup` class provides a more modern alternative to :"
"func:`create_task`. Using this API, the last example becomes::"
msgstr ""

#: ../../library/asyncio-task.rst:114
msgid ""
"async def main():\n"
"    async with asyncio.TaskGroup() as tg:\n"
"        task1 = tg.create_task(\n"
"            say_after(1, 'hello'))\n"
"\n"
"        task2 = tg.create_task(\n"
"            say_after(2, 'world'))\n"
"\n"
"        print(f\"started at {time.strftime('%X')}\")\n"
"\n"
"    # The await is implicit when the context manager exits.\n"
"\n"
"    print(f\"finished at {time.strftime('%X')}\")"
msgstr ""

#: ../../library/asyncio-task.rst:128
msgid "The timing and output should be the same as for the previous version."
msgstr ""

#: ../../library/asyncio-task.rst:130
msgid ":class:`asyncio.TaskGroup`."
msgstr ""

#: ../../library/asyncio-task.rst:137
msgid "Awaitables"
msgstr "Aguardáveis"

#: ../../library/asyncio-task.rst:139
msgid ""
"We say that an object is an **awaitable** object if it can be used in an :"
"keyword:`await` expression.  Many asyncio APIs are designed to accept "
"awaitables."
msgstr ""
"Dizemos que um objeto é um objeto **aguardável** se ele pode ser usado em "
"uma expressão :keyword:`await`. Muitas APIs asyncio são projetadas para "
"aceitar aguardáveis."

#: ../../library/asyncio-task.rst:143
msgid ""
"There are three main types of *awaitable* objects: **coroutines**, "
"**Tasks**, and **Futures**."
msgstr ""
"Existem três tipos principais de objetos *aguardáveis*: **corrotinas**, "
"**Tarefas**, e **Futuros**."

#: ../../library/asyncio-task.rst:149
msgid ""
"Python coroutines are *awaitables* and therefore can be awaited from other "
"coroutines::"
msgstr ""
"Corrotinas Python são *aguardáveis* e portanto podem ser aguardadas a partir "
"de outras corrotinas::"

#: ../../library/asyncio-task.rst:152
msgid ""
"import asyncio\n"
"\n"
"async def nested():\n"
"    return 42\n"
"\n"
"async def main():\n"
"    # Nothing happens if we just call \"nested()\".\n"
"    # A coroutine object is created but not awaited,\n"
"    # so it *won't run at all*.\n"
"    nested()\n"
"\n"
"    # Let's do it differently now and await it:\n"
"    print(await nested())  # will print \"42\".\n"
"\n"
"asyncio.run(main())"
msgstr ""

#: ../../library/asyncio-task.rst:170
msgid ""
"In this documentation the term \"coroutine\" can be used for two closely "
"related concepts:"
msgstr ""
"Nesta documentação, o termo \"corrotina\" pode ser usado para dois conceitos "
"intimamente relacionados:"

#: ../../library/asyncio-task.rst:173
msgid "a *coroutine function*: an :keyword:`async def` function;"
msgstr "uma *função de corrotina*: uma função :keyword:`async def`;"

#: ../../library/asyncio-task.rst:175
msgid ""
"a *coroutine object*: an object returned by calling a *coroutine function*."
msgstr ""
"um *objeto de corrotina*: um objeto retornado ao chamar uma *função de "
"corrotina*."

#: ../../library/asyncio-task.rst:180
msgid "Tasks"
msgstr "Tarefas"

#: ../../library/asyncio-task.rst:181
msgid "*Tasks* are used to schedule coroutines *concurrently*."
msgstr "*Tarefas* são usadas para agendar corrotinas *concorrentemente*."

#: ../../library/asyncio-task.rst:183
msgid ""
"When a coroutine is wrapped into a *Task* with functions like :func:`asyncio."
"create_task` the coroutine is automatically scheduled to run soon::"
msgstr ""
"Quando uma corrotina é envolta em uma *tarefa* com funções como :func:"
"`asyncio.create_task`, a corrotina é automaticamente agendada para executar "
"em breve::"

#: ../../library/asyncio-task.rst:187
msgid ""
"import asyncio\n"
"\n"
"async def nested():\n"
"    return 42\n"
"\n"
"async def main():\n"
"    # Schedule nested() to run soon concurrently\n"
"    # with \"main()\".\n"
"    task = asyncio.create_task(nested())\n"
"\n"
"    # \"task\" can now be used to cancel \"nested()\", or\n"
"    # can simply be awaited to wait until it is complete:\n"
"    await task\n"
"\n"
"asyncio.run(main())"
msgstr ""

#: ../../library/asyncio-task.rst:205
msgid "Futures"
msgstr "Futuros"

#: ../../library/asyncio-task.rst:206
msgid ""
"A :class:`Future` is a special **low-level** awaitable object that "
"represents an **eventual result** of an asynchronous operation."
msgstr ""
"Um :class:`Future` é um objeto aguardável especial de **baixo nível** que "
"representa um **resultado eventual** de uma operação assíncrona."

#: ../../library/asyncio-task.rst:209
msgid ""
"When a Future object is *awaited* it means that the coroutine will wait "
"until the Future is resolved in some other place."
msgstr ""
"Quando um objeto Future é *aguardado* isso significa que a corrotina irá "
"esperar até que o Future seja resolvido em algum outro local."

#: ../../library/asyncio-task.rst:212
msgid ""
"Future objects in asyncio are needed to allow callback-based code to be used "
"with async/await."
msgstr ""
"Objetos Future em asyncio são necessários para permitir que código baseado "
"em função de retorno seja utilizado com async/await."

#: ../../library/asyncio-task.rst:215
msgid ""
"Normally **there is no need** to create Future objects at the application "
"level code."
msgstr ""
"Normalmente **não existe necessidade** em criar objetos Future no nível de "
"código da aplicação."

#: ../../library/asyncio-task.rst:218
msgid ""
"Future objects, sometimes exposed by libraries and some asyncio APIs, can be "
"awaited::"
msgstr ""
"Objetos Future, algumas vezes expostos por bibliotecas e algumas APIs "
"asyncio, podem ser aguardados::"

#: ../../library/asyncio-task.rst:221
msgid ""
"async def main():\n"
"    await function_that_returns_a_future_object()\n"
"\n"
"    # this is also valid:\n"
"    await asyncio.gather(\n"
"        function_that_returns_a_future_object(),\n"
"        some_python_coroutine()\n"
"    )"
msgstr ""

#: ../../library/asyncio-task.rst:230
msgid ""
"A good example of a low-level function that returns a Future object is :meth:"
"`loop.run_in_executor`."
msgstr ""
"Um bom exemplo de uma função de baixo nível que retorna um objeto Future é :"
"meth:`loop.run_in_executor`."

#: ../../library/asyncio-task.rst:235
msgid "Creating Tasks"
msgstr "Criando Tarefas"

#: ../../library/asyncio-task.rst:237
msgid "**Source code:** :source:`Lib/asyncio/tasks.py`"
msgstr ""

#: ../../library/asyncio-task.rst:243
msgid ""
"Wrap the *coro* :ref:`coroutine <coroutine>` into a :class:`Task` and "
"schedule its execution.  Return the Task object."
msgstr ""
"Envolva a :ref:`corrotina <coroutine>` *coro* em uma :class:`Task` e agende "
"sua execução. Retorne o objeto Task."

#: ../../library/asyncio-task.rst:246
msgid ""
"If *name* is not ``None``, it is set as the name of the task using :meth:"
"`Task.set_name`."
msgstr ""
"Se *name* não for ``None``, ele é setado como o nome da tarefa usando :meth:"
"`Task.set_name`."

#: ../../library/asyncio-task.rst:249
msgid ""
"An optional keyword-only *context* argument allows specifying a custom :"
"class:`contextvars.Context` for the *coro* to run in. The current context "
"copy is created when no *context* is provided."
msgstr ""

#: ../../library/asyncio-task.rst:253
msgid ""
"The task is executed in the loop returned by :func:`get_running_loop`, :exc:"
"`RuntimeError` is raised if there is no running loop in current thread."
msgstr ""
"A tarefa é executada no laço e retornada por :func:`get_running_loop`, :exc:"
"`RuntimeError` é levantado se não existir nenhum loop na thread atual."

#: ../../library/asyncio-task.rst:259
msgid ""
":meth:`asyncio.TaskGroup.create_task` is a new alternative leveraging "
"structural concurrency; it allows for waiting for a group of related tasks "
"with strong safety guarantees."
msgstr ""

#: ../../library/asyncio-task.rst:265
msgid ""
"Save a reference to the result of this function, to avoid a task "
"disappearing mid-execution. The event loop only keeps weak references to "
"tasks. A task that isn't referenced elsewhere may get garbage collected at "
"any time, even before it's done. For reliable \"fire-and-forget\" background "
"tasks, gather them in a collection::"
msgstr ""
"Mantenha uma referência para o resultado dessa função, evitando assim que "
"uma tarefa desapareça durante a execução. O laço de eventos mantém apenas "
"referências fracas para as tarefas. Uma tarefa que não é referenciada por "
"nada mais pode ser removida pelo coletor de lixo a qualquer momento, antes "
"mesmo da função ser finalizada. Para tarefas de segundo plano \"atire-e-"
"esqueça\", junte-as em uma coleção::"

#: ../../library/asyncio-task.rst:272
msgid ""
"background_tasks = set()\n"
"\n"
"for i in range(10):\n"
"    task = asyncio.create_task(some_coro(param=i))\n"
"\n"
"    # Add task to the set. This creates a strong reference.\n"
"    background_tasks.add(task)\n"
"\n"
"    # To prevent keeping references to finished tasks forever,\n"
"    # make each task remove its own reference from the set after\n"
"    # completion:\n"
"    task.add_done_callback(background_tasks.discard)"
msgstr ""

#: ../../library/asyncio-task.rst:287 ../../library/asyncio-task.rst:1075
msgid "Added the *name* parameter."
msgstr "Adicionado o parâmetro *name*."

#: ../../library/asyncio-task.rst:290 ../../library/asyncio-task.rst:1082
msgid "Added the *context* parameter."
msgstr "Adicionado o parâmetro *context*."

#: ../../library/asyncio-task.rst:295
msgid "Task Cancellation"
msgstr ""

#: ../../library/asyncio-task.rst:297
msgid ""
"Tasks can easily and safely be cancelled. When a task is cancelled, :exc:"
"`asyncio.CancelledError` will be raised in the task at the next opportunity."
msgstr ""

#: ../../library/asyncio-task.rst:301
msgid ""
"It is recommended that coroutines use ``try/finally`` blocks to robustly "
"perform clean-up logic. In case :exc:`asyncio.CancelledError` is explicitly "
"caught, it should generally be propagated when clean-up is complete. :exc:"
"`asyncio.CancelledError` directly subclasses :exc:`BaseException` so most "
"code will not need to be aware of it."
msgstr ""

#: ../../library/asyncio-task.rst:307
msgid ""
"The asyncio components that enable structured concurrency, like :class:"
"`asyncio.TaskGroup` and :func:`asyncio.timeout`, are implemented using "
"cancellation internally and might misbehave if a coroutine swallows :exc:"
"`asyncio.CancelledError`. Similarly, user code should not generally call :"
"meth:`uncancel <asyncio.Task.uncancel>`. However, in cases when suppressing :"
"exc:`asyncio.CancelledError` is truly desired, it is necessary to also call "
"``uncancel()`` to completely remove the cancellation state."
msgstr ""

#: ../../library/asyncio-task.rst:319
msgid "Task Groups"
msgstr ""

#: ../../library/asyncio-task.rst:321
msgid ""
"Task groups combine a task creation API with a convenient and reliable way "
"to wait for all tasks in the group to finish."
msgstr ""

#: ../../library/asyncio-task.rst:326
msgid ""
"An :ref:`asynchronous context manager <async-context-managers>` holding a "
"group of tasks. Tasks can be added to the group using :meth:`create_task`. "
"All tasks are awaited when the context manager exits."
msgstr ""

#: ../../library/asyncio-task.rst:335
msgid ""
"Create a task in this task group. The signature matches that of :func:"
"`asyncio.create_task`."
msgstr ""

#: ../../library/asyncio-task.rst:338 ../../library/asyncio-task.rst:472
#: ../../library/asyncio-task.rst:645 ../../library/asyncio-task.rst:703
#: ../../library/asyncio-task.rst:729 ../../library/asyncio-task.rst:769
#: ../../library/asyncio-task.rst:868
msgid "Example::"
msgstr "Exemplo::"

#: ../../library/asyncio-task.rst:340
msgid ""
"async def main():\n"
"    async with asyncio.TaskGroup() as tg:\n"
"        task1 = tg.create_task(some_coro(...))\n"
"        task2 = tg.create_task(another_coro(...))\n"
"    print(f\"Both tasks have completed now: {task1.result()}, {task2."
"result()}\")"
msgstr ""

#: ../../library/asyncio-task.rst:346
msgid ""
"The ``async with`` statement will wait for all tasks in the group to finish. "
"While waiting, new tasks may still be added to the group (for example, by "
"passing ``tg`` into one of the coroutines and calling ``tg.create_task()`` "
"in that coroutine). Once the last task has finished and the ``async with`` "
"block is exited, no new tasks may be added to the group."
msgstr ""

#: ../../library/asyncio-task.rst:353
msgid ""
"The first time any of the tasks belonging to the group fails with an "
"exception other than :exc:`asyncio.CancelledError`, the remaining tasks in "
"the group are cancelled. No further tasks can then be added to the group. At "
"this point, if the body of the ``async with`` statement is still active (i."
"e., :meth:`~object.__aexit__` hasn't been called yet), the task directly "
"containing the ``async with`` statement is also cancelled. The resulting :"
"exc:`asyncio.CancelledError` will interrupt an ``await``, but it will not "
"bubble out of the containing ``async with`` statement."
msgstr ""

#: ../../library/asyncio-task.rst:363
msgid ""
"Once all tasks have finished, if any tasks have failed with an exception "
"other than :exc:`asyncio.CancelledError`, those exceptions are combined in "
"an :exc:`ExceptionGroup` or :exc:`BaseExceptionGroup` (as appropriate; see "
"their documentation) which is then raised."
msgstr ""

#: ../../library/asyncio-task.rst:370
msgid ""
"Two base exceptions are treated specially: If any task fails with :exc:"
"`KeyboardInterrupt` or :exc:`SystemExit`, the task group still cancels the "
"remaining tasks and waits for them, but then the initial :exc:"
"`KeyboardInterrupt` or :exc:`SystemExit` is re-raised instead of :exc:"
"`ExceptionGroup` or :exc:`BaseExceptionGroup`."
msgstr ""

#: ../../library/asyncio-task.rst:376
msgid ""
"If the body of the ``async with`` statement exits with an exception (so :"
"meth:`~object.__aexit__` is called with an exception set), this is treated "
"the same as if one of the tasks failed: the remaining tasks are cancelled "
"and then waited for, and non-cancellation exceptions are grouped into an "
"exception group and raised. The exception passed into :meth:`~object."
"__aexit__`, unless it is :exc:`asyncio.CancelledError`, is also included in "
"the exception group. The same special case is made for :exc:"
"`KeyboardInterrupt` and :exc:`SystemExit` as in the previous paragraph."
msgstr ""

#: ../../library/asyncio-task.rst:390
msgid "Sleeping"
msgstr "Dormindo"

#: ../../library/asyncio-task.rst:394
msgid "Block for *delay* seconds."
msgstr "Bloqueia por *delay* segundos."

#: ../../library/asyncio-task.rst:396
msgid ""
"If *result* is provided, it is returned to the caller when the coroutine "
"completes."
msgstr ""
"Se *result* é fornecido, é retornado para o autor da chamada quando a "
"corrotina termina."

#: ../../library/asyncio-task.rst:399
msgid ""
"``sleep()`` always suspends the current task, allowing other tasks to run."
msgstr ""
"``sleep()`` sempre suspende a tarefa atual, permitindo que outras tarefas "
"sejam executadas."

#: ../../library/asyncio-task.rst:402
msgid ""
"Setting the delay to 0 provides an optimized path to allow other tasks to "
"run. This can be used by long-running functions to avoid blocking the event "
"loop for the full duration of the function call."
msgstr ""
"Configurando o delay para 0 fornece um caminho otimizado para permitir que "
"outras tarefas executem. Isto pode ser usado por funções de longa execução "
"para evitar que bloqueiem o laço de eventos por toda a duração da chamada da "
"função."

#: ../../library/asyncio-task.rst:408
msgid ""
"Example of coroutine displaying the current date every second for 5 seconds::"
msgstr ""
"Exemplo de uma corrotina exibindo a data atual a cada segundo durante 5 "
"segundos::"

#: ../../library/asyncio-task.rst:411
msgid ""
"import asyncio\n"
"import datetime\n"
"\n"
"async def display_date():\n"
"    loop = asyncio.get_running_loop()\n"
"    end_time = loop.time() + 5.0\n"
"    while True:\n"
"        print(datetime.datetime.now())\n"
"        if (loop.time() + 1.0) >= end_time:\n"
"            break\n"
"        await asyncio.sleep(1)\n"
"\n"
"asyncio.run(display_date())"
msgstr ""

#: ../../library/asyncio-task.rst:426 ../../library/asyncio-task.rst:521
#: ../../library/asyncio-task.rst:620 ../../library/asyncio-task.rst:794
#: ../../library/asyncio-task.rst:848 ../../library/asyncio-task.rst:874
msgid "Removed the *loop* parameter."
msgstr "Removido o parâmetro *loop*."

#: ../../library/asyncio-task.rst:431
msgid "Running Tasks Concurrently"
msgstr "Executando tarefas concorrentemente"

#: ../../library/asyncio-task.rst:435
msgid ""
"Run :ref:`awaitable objects <asyncio-awaitables>` in the *aws* sequence "
"*concurrently*."
msgstr ""
"Executa :ref:`objetos aguardáveis <asyncio-awaitables>` na sequência *aws* "
"de forma *concorrente*."

#: ../../library/asyncio-task.rst:438
msgid ""
"If any awaitable in *aws* is a coroutine, it is automatically scheduled as a "
"Task."
msgstr ""
"Se qualquer aguardável em *aws* é uma corrotina, ele é automaticamente "
"agendado como uma Tarefa."

#: ../../library/asyncio-task.rst:441
msgid ""
"If all awaitables are completed successfully, the result is an aggregate "
"list of returned values.  The order of result values corresponds to the "
"order of awaitables in *aws*."
msgstr ""
"Se todos os aguardáveis forem concluídos com sucesso, o resultado é uma "
"lista agregada de valores retornados. A ordem dos valores resultantes "
"corresponde a ordem dos aguardáveis em *aws*."

#: ../../library/asyncio-task.rst:445
msgid ""
"If *return_exceptions* is ``False`` (default), the first raised exception is "
"immediately propagated to the task that awaits on ``gather()``.  Other "
"awaitables in the *aws* sequence **won't be cancelled** and will continue to "
"run."
msgstr ""
"Se *return_exceptions* for ``False`` (valor padrão), a primeira exceção "
"levantada é imediatamente propagada para a tarefa que espera em "
"``gather()``. Outros aguardáveis na sequência *aws* **não serão cancelados** "
"e irão continuar a executar."

#: ../../library/asyncio-task.rst:450
msgid ""
"If *return_exceptions* is ``True``, exceptions are treated the same as "
"successful results, and aggregated in the result list."
msgstr ""
"Se *return_exceptions* for ``True``, exceções são tratadas da mesma forma "
"que resultados com sucesso, e agregadas na lista de resultados."

#: ../../library/asyncio-task.rst:453
msgid ""
"If ``gather()`` is *cancelled*, all submitted awaitables (that have not "
"completed yet) are also *cancelled*."
msgstr ""
"Se ``gather()`` for *cancelado*, todos os aguardáveis que foram submetidos "
"(que não foram concluídos ainda) também são *cancelados*."

#: ../../library/asyncio-task.rst:456
msgid ""
"If any Task or Future from the *aws* sequence is *cancelled*, it is treated "
"as if it raised :exc:`CancelledError` -- the ``gather()`` call is **not** "
"cancelled in this case.  This is to prevent the cancellation of one "
"submitted Task/Future to cause other Tasks/Futures to be cancelled."
msgstr ""
"Se qualquer Tarefa ou Futuro da sequência *aws* for *cancelado*, ele é "
"tratado como se tivesse levantado :exc:`CancelledError` -- a chamada para "
"``gather()`` **não** é cancelada neste caso. Isso existe para prevenir que o "
"cancelamento de uma Tarefa/Futuro submetida ocasione outras Tarefas/Futuros "
"a serem cancelados."

#: ../../library/asyncio-task.rst:463
msgid ""
"A new alternative to create and run tasks concurrently and wait for their "
"completion is :class:`asyncio.TaskGroup`. *TaskGroup* provides stronger "
"safety guarantees than *gather* for scheduling a nesting of subtasks: if a "
"task (or a subtask, a task scheduled by a task) raises an exception, "
"*TaskGroup* will, while *gather* will not, cancel the remaining scheduled "
"tasks)."
msgstr ""

#: ../../library/asyncio-task.rst:474
msgid ""
"import asyncio\n"
"\n"
"async def factorial(name, number):\n"
"    f = 1\n"
"    for i in range(2, number + 1):\n"
"        print(f\"Task {name}: Compute factorial({number}), currently i={i}..."
"\")\n"
"        await asyncio.sleep(1)\n"
"        f *= i\n"
"    print(f\"Task {name}: factorial({number}) = {f}\")\n"
"    return f\n"
"\n"
"async def main():\n"
"    # Schedule three calls *concurrently*:\n"
"    L = await asyncio.gather(\n"
"        factorial(\"A\", 2),\n"
"        factorial(\"B\", 3),\n"
"        factorial(\"C\", 4),\n"
"    )\n"
"    print(L)\n"
"\n"
"asyncio.run(main())\n"
"\n"
"# Expected output:\n"
"#\n"
"#     Task A: Compute factorial(2), currently i=2...\n"
"#     Task B: Compute factorial(3), currently i=2...\n"
"#     Task C: Compute factorial(4), currently i=2...\n"
"#     Task A: factorial(2) = 2\n"
"#     Task B: Compute factorial(3), currently i=3...\n"
"#     Task C: Compute factorial(4), currently i=3...\n"
"#     Task B: factorial(3) = 6\n"
"#     Task C: Compute factorial(4), currently i=4...\n"
"#     Task C: factorial(4) = 24\n"
"#     [2, 6, 24]"
msgstr ""

#: ../../library/asyncio-task.rst:510
msgid ""
"If *return_exceptions* is false, cancelling gather() after it has been "
"marked done won't cancel any submitted awaitables. For instance, gather can "
"be marked done after propagating an exception to the caller, therefore, "
"calling ``gather.cancel()`` after catching an exception (raised by one of "
"the awaitables) from gather won't cancel any other awaitables."
msgstr ""

#: ../../library/asyncio-task.rst:517
msgid ""
"If the *gather* itself is cancelled, the cancellation is propagated "
"regardless of *return_exceptions*."
msgstr ""
"Se *gather* por si mesmo for cancelado, o cancelamento é propagado "
"independente de *return_exceptions*."

#: ../../library/asyncio-task.rst:524
msgid ""
"Deprecation warning is emitted if no positional arguments are provided or "
"not all positional arguments are Future-like objects and there is no running "
"event loop."
msgstr ""
"Aviso de descontinuidade é emitido se nenhum argumento posicional for "
"fornecido, ou nem todos os argumentos posicionais são objetos similar a "
"Futuro, e não existe nenhum laço de eventos em execução."

#: ../../library/asyncio-task.rst:533
msgid "Eager Task Factory"
msgstr ""

#: ../../library/asyncio-task.rst:537
msgid "A task factory for eager task execution."
msgstr ""

#: ../../library/asyncio-task.rst:539
msgid ""
"When using this factory (via :meth:`loop.set_task_factory(asyncio."
"eager_task_factory) <loop.set_task_factory>`), coroutines begin execution "
"synchronously during :class:`Task` construction. Tasks are only scheduled on "
"the event loop if they block. This can be a performance improvement as the "
"overhead of loop scheduling is avoided for coroutines that complete "
"synchronously."
msgstr ""

#: ../../library/asyncio-task.rst:545
msgid ""
"A common example where this is beneficial is coroutines which employ caching "
"or memoization to avoid actual I/O when possible."
msgstr ""

#: ../../library/asyncio-task.rst:550
msgid ""
"Immediate execution of the coroutine is a semantic change. If the coroutine "
"returns or raises, the task is never scheduled to the event loop. If the "
"coroutine execution blocks, the task is scheduled to the event loop. This "
"change may introduce behavior changes to existing applications. For example, "
"the application's task execution order is likely to change."
msgstr ""

#: ../../library/asyncio-task.rst:561
msgid ""
"Create an eager task factory, similar to :func:`eager_task_factory`, using "
"the provided *custom_task_constructor* when creating a new task instead of "
"the default :class:`Task`."
msgstr ""

#: ../../library/asyncio-task.rst:565
msgid ""
"*custom_task_constructor* must be a *callable* with the signature matching "
"the signature of :class:`Task.__init__ <Task>`. The callable must return a :"
"class:`asyncio.Task`-compatible object."
msgstr ""

#: ../../library/asyncio-task.rst:569
msgid ""
"This function returns a *callable* intended to be used as a task factory of "
"an event loop via :meth:`loop.set_task_factory(factory) <loop."
"set_task_factory>`)."
msgstr ""

#: ../../library/asyncio-task.rst:576
msgid "Shielding From Cancellation"
msgstr "Protegendo contra cancelamento"

#: ../../library/asyncio-task.rst:580
msgid ""
"Protect an :ref:`awaitable object <asyncio-awaitables>` from being :meth:"
"`cancelled <Task.cancel>`."
msgstr ""
"Protege um :ref:`objeto aguardável <asyncio-awaitables>` de ser :meth:"
"`cancelado <Task.cancel>`."

#: ../../library/asyncio-task.rst:583 ../../library/asyncio-task.rst:749
msgid "If *aw* is a coroutine it is automatically scheduled as a Task."
msgstr ""
"Se *aw* é uma corrotina, ela é automaticamente agendada como uma Tarefa."

#: ../../library/asyncio-task.rst:585
msgid "The statement::"
msgstr "A instrução::"

#: ../../library/asyncio-task.rst:587
msgid ""
"task = asyncio.create_task(something())\n"
"res = await shield(task)"
msgstr ""

#: ../../library/asyncio-task.rst:590
msgid "is equivalent to::"
msgstr "é equivalente a::"

#: ../../library/asyncio-task.rst:592
msgid "res = await something()"
msgstr ""

#: ../../library/asyncio-task.rst:594
msgid ""
"*except* that if the coroutine containing it is cancelled, the Task running "
"in ``something()`` is not cancelled.  From the point of view of "
"``something()``, the cancellation did not happen. Although its caller is "
"still cancelled, so the \"await\" expression still raises a :exc:"
"`CancelledError`."
msgstr ""
"*exceto* que se a corrotina contendo-a for cancelada, a Tarefa executando em "
"``something()`` não é cancelada. Do ponto de vista de ``something()``, o "
"cancelamento não aconteceu. Apesar do autor da chamada ainda estar "
"cancelado, então a expressão \"await\" ainda levanta um :exc:"
"`CancelledError`."

#: ../../library/asyncio-task.rst:600
msgid ""
"If ``something()`` is cancelled by other means (i.e. from within itself) "
"that would also cancel ``shield()``."
msgstr ""
"Se ``something()`` é cancelada por outros meios (isto é, dentro ou a partir "
"de si mesma) isso também iria cancelar ``shield()``."

#: ../../library/asyncio-task.rst:603
msgid ""
"If it is desired to completely ignore cancellation (not recommended) the "
"``shield()`` function should be combined with a try/except clause, as "
"follows::"
msgstr ""
"Se for desejado ignorar completamente os cancelamentos (não recomendado) a "
"função ``shield()`` deve ser combinada com uma cláusula try/except, conforme "
"abaixo::"

#: ../../library/asyncio-task.rst:607
msgid ""
"task = asyncio.create_task(something())\n"
"try:\n"
"    res = await shield(task)\n"
"except CancelledError:\n"
"    res = None"
msgstr ""

#: ../../library/asyncio-task.rst:615
msgid ""
"Save a reference to tasks passed to this function, to avoid a task "
"disappearing mid-execution. The event loop only keeps weak references to "
"tasks. A task that isn't referenced elsewhere may get garbage collected at "
"any time, even before it's done."
msgstr ""
"Mantenha uma referência para as tarefas passadas para essa função função, "
"evitando assim que uma tarefa desapareça durante a execução. O laço de "
"eventos mantém apenas referências fracas para as tarefas. Uma tarefa que não "
"é referenciada por nada mais pode ser removida pelo coletor de lixo a "
"qualquer momento, antes mesmo da função ser finalizada."

#: ../../library/asyncio-task.rst:623
msgid ""
"Deprecation warning is emitted if *aw* is not Future-like object and there "
"is no running event loop."
msgstr ""
"Aviso de descontinuidade é emitido se *aw* não é um objeto similar a Futuro, "
"e não existe nenhum laço de eventos em execução."

#: ../../library/asyncio-task.rst:629
msgid "Timeouts"
msgstr "Tempo limite"

#: ../../library/asyncio-task.rst:633
msgid ""
"Return an :ref:`asynchronous context manager <async-context-managers>` that "
"can be used to limit the amount of time spent waiting on something."
msgstr ""

#: ../../library/asyncio-task.rst:637
msgid ""
"*delay* can either be ``None``, or a float/int number of seconds to wait. If "
"*delay* is ``None``, no time limit will be applied; this can be useful if "
"the delay is unknown when the context manager is created."
msgstr ""

#: ../../library/asyncio-task.rst:642
msgid ""
"In either case, the context manager can be rescheduled after creation using :"
"meth:`Timeout.reschedule`."
msgstr ""

#: ../../library/asyncio-task.rst:647
msgid ""
"async def main():\n"
"    async with asyncio.timeout(10):\n"
"        await long_running_task()"
msgstr ""

#: ../../library/asyncio-task.rst:651
msgid ""
"If ``long_running_task`` takes more than 10 seconds to complete, the context "
"manager will cancel the current task and handle the resulting :exc:`asyncio."
"CancelledError` internally, transforming it into a :exc:`TimeoutError` which "
"can be caught and handled."
msgstr ""

#: ../../library/asyncio-task.rst:658
msgid ""
"The :func:`asyncio.timeout` context manager is what transforms the :exc:"
"`asyncio.CancelledError` into a :exc:`TimeoutError`, which means the :exc:"
"`TimeoutError` can only be caught *outside* of the context manager."
msgstr ""

#: ../../library/asyncio-task.rst:663
msgid "Example of catching :exc:`TimeoutError`::"
msgstr ""

#: ../../library/asyncio-task.rst:665
msgid ""
"async def main():\n"
"    try:\n"
"        async with asyncio.timeout(10):\n"
"            await long_running_task()\n"
"    except TimeoutError:\n"
"        print(\"The long operation timed out, but we've handled it.\")\n"
"\n"
"    print(\"This statement will run regardless.\")"
msgstr ""

#: ../../library/asyncio-task.rst:674
msgid ""
"The context manager produced by :func:`asyncio.timeout` can be rescheduled "
"to a different deadline and inspected."
msgstr ""

#: ../../library/asyncio-task.rst:679
msgid ""
"An :ref:`asynchronous context manager <async-context-managers>` for "
"cancelling overdue coroutines."
msgstr ""

#: ../../library/asyncio-task.rst:682
msgid ""
"``when`` should be an absolute time at which the context should time out, as "
"measured by the event loop's clock:"
msgstr ""

#: ../../library/asyncio-task.rst:685
msgid "If ``when`` is ``None``, the timeout will never trigger."
msgstr ""

#: ../../library/asyncio-task.rst:686
msgid ""
"If ``when < loop.time()``, the timeout will trigger on the next iteration of "
"the event loop."
msgstr ""

#: ../../library/asyncio-task.rst:691
msgid ""
"Return the current deadline, or ``None`` if the current deadline is not set."
msgstr ""

#: ../../library/asyncio-task.rst:696
msgid "Reschedule the timeout."
msgstr ""

#: ../../library/asyncio-task.rst:700
msgid "Return whether the context manager has exceeded its deadline (expired)."
msgstr ""

#: ../../library/asyncio-task.rst:705
msgid ""
"async def main():\n"
"    try:\n"
"        # We do not know the timeout when starting, so we pass ``None``.\n"
"        async with asyncio.timeout(None) as cm:\n"
"            # We know the timeout now, so we reschedule it.\n"
"            new_deadline = get_running_loop().time() + 10\n"
"            cm.reschedule(new_deadline)\n"
"\n"
"            await long_running_task()\n"
"    except TimeoutError:\n"
"        pass\n"
"\n"
"    if cm.expired():\n"
"        print(\"Looks like we haven't finished on time.\")"
msgstr ""

#: ../../library/asyncio-task.rst:720
msgid "Timeout context managers can be safely nested."
msgstr ""

#: ../../library/asyncio-task.rst:726
msgid ""
"Similar to :func:`asyncio.timeout`, except *when* is the absolute time to "
"stop waiting, or ``None``."
msgstr ""

#: ../../library/asyncio-task.rst:731
msgid ""
"async def main():\n"
"    loop = get_running_loop()\n"
"    deadline = loop.time() + 20\n"
"    try:\n"
"        async with asyncio.timeout_at(deadline):\n"
"            await long_running_task()\n"
"    except TimeoutError:\n"
"        print(\"The long operation timed out, but we've handled it.\")\n"
"\n"
"    print(\"This statement will run regardless.\")"
msgstr ""

#: ../../library/asyncio-task.rst:746
msgid ""
"Wait for the *aw* :ref:`awaitable <asyncio-awaitables>` to complete with a "
"timeout."
msgstr ""
"Espera o :ref:`aguardável <asyncio-awaitables>` *aw* concluir sem "
"ultrapassar o tempo limite \"timeout\"."

#: ../../library/asyncio-task.rst:751
msgid ""
"*timeout* can either be ``None`` or a float or int number of seconds to wait "
"for.  If *timeout* is ``None``, block until the future completes."
msgstr ""
"*timeout* pode ser ``None``, ou um ponto flutuante, ou um número inteiro de "
"segundos para aguardar. Se *timeout* é ``None``, aguarda até o future "
"encerrar."

#: ../../library/asyncio-task.rst:755
msgid ""
"If a timeout occurs, it cancels the task and raises :exc:`TimeoutError`."
msgstr ""

#: ../../library/asyncio-task.rst:758
msgid ""
"To avoid the task :meth:`cancellation <Task.cancel>`, wrap it in :func:"
"`shield`."
msgstr ""
"Para evitar o :meth:`cancelamento <Task.cancel>` da tarefa, envolva-a com :"
"func:`shield`."

#: ../../library/asyncio-task.rst:761
msgid ""
"The function will wait until the future is actually cancelled, so the total "
"wait time may exceed the *timeout*. If an exception happens during "
"cancellation, it is propagated."
msgstr ""
"A função irá aguardar até o future ser realmente cancelado, então o tempo "
"total de espera pode exceder o tempo limite *timeout*. Se uma exceção "
"ocorrer durante o cancelamento, ela será propagada."

#: ../../library/asyncio-task.rst:765
msgid "If the wait is cancelled, the future *aw* is also cancelled."
msgstr "Se ele for cancelado, o future *aw* também é cancelado."

#: ../../library/asyncio-task.rst:771
msgid ""
"async def eternity():\n"
"    # Sleep for one hour\n"
"    await asyncio.sleep(3600)\n"
"    print('yay!')\n"
"\n"
"async def main():\n"
"    # Wait for at most 1 second\n"
"    try:\n"
"        await asyncio.wait_for(eternity(), timeout=1.0)\n"
"    except TimeoutError:\n"
"        print('timeout!')\n"
"\n"
"asyncio.run(main())\n"
"\n"
"# Expected output:\n"
"#\n"
"#     timeout!"
msgstr ""

#: ../../library/asyncio-task.rst:789
msgid ""
"When *aw* is cancelled due to a timeout, ``wait_for`` waits for *aw* to be "
"cancelled.  Previously, it raised :exc:`TimeoutError` immediately."
msgstr ""

#: ../../library/asyncio-task.rst:797
msgid "Raises :exc:`TimeoutError` instead of :exc:`asyncio.TimeoutError`."
msgstr ""

#: ../../library/asyncio-task.rst:802
msgid "Waiting Primitives"
msgstr "Primitivas de Espera"

#: ../../library/asyncio-task.rst:806
msgid ""
"Run :class:`~asyncio.Future` and :class:`~asyncio.Task` instances in the "
"*aws* iterable concurrently and block until the condition specified by "
"*return_when*."
msgstr ""

#: ../../library/asyncio-task.rst:810
msgid "The *aws* iterable must not be empty."
msgstr "O iterável *aws* não deve ser vazio."

#: ../../library/asyncio-task.rst:812
msgid "Returns two sets of Tasks/Futures: ``(done, pending)``."
msgstr "Retorna dois conjuntos de Tarefas/Futuros: ``(done, pending)``."

#: ../../library/asyncio-task.rst:814
msgid "Usage::"
msgstr "Uso::"

#: ../../library/asyncio-task.rst:816
msgid "done, pending = await asyncio.wait(aws)"
msgstr ""

#: ../../library/asyncio-task.rst:818
msgid ""
"*timeout* (a float or int), if specified, can be used to control the maximum "
"number of seconds to wait before returning."
msgstr ""
"*timeout* (um ponto flutuante ou inteiro), se especificado, pode ser usado "
"para controlar o número máximo de segundos para aguardar antes de retornar."

#: ../../library/asyncio-task.rst:821
msgid ""
"Note that this function does not raise :exc:`TimeoutError`. Futures or Tasks "
"that aren't done when the timeout occurs are simply returned in the second "
"set."
msgstr ""

#: ../../library/asyncio-task.rst:825
msgid ""
"*return_when* indicates when this function should return.  It must be one of "
"the following constants:"
msgstr ""
"*return_when* indica quando esta função deve retornar. Ele deve ser uma das "
"seguintes constantes:"

#: ../../library/asyncio-task.rst:831
msgid "Constant"
msgstr "Constante"

#: ../../library/asyncio-task.rst:832
msgid "Description"
msgstr "Descrição"

#: ../../library/asyncio-task.rst:835
msgid "The function will return when any future finishes or is cancelled."
msgstr ""
"A função irá retornar quando qualquer futuro terminar ou for cancelado."

#: ../../library/asyncio-task.rst:838
msgid ""
"The function will return when any future finishes by raising an exception. "
"If no future raises an exception then it is equivalent to :const:"
"`ALL_COMPLETED`."
msgstr ""

#: ../../library/asyncio-task.rst:843
msgid "The function will return when all futures finish or are cancelled."
msgstr ""
"A função irá retornar quando todos os futuros encerrarem ou forem cancelados."

#: ../../library/asyncio-task.rst:845
msgid ""
"Unlike :func:`~asyncio.wait_for`, ``wait()`` does not cancel the futures "
"when a timeout occurs."
msgstr ""
"Diferente de :func:`~asyncio.wait_for`, ``wait()`` não cancela os futuros "
"quando um tempo limite é atingido."

#: ../../library/asyncio-task.rst:851
msgid "Passing coroutine objects to ``wait()`` directly is forbidden."
msgstr ""

#: ../../library/asyncio-task.rst:854 ../../library/asyncio-task.rst:881
msgid "Added support for generators yielding tasks."
msgstr ""

#: ../../library/asyncio-task.rst:860
msgid ""
"Run :ref:`awaitable objects <asyncio-awaitables>` in the *aws* iterable "
"concurrently.  Return an iterator of coroutines. Each coroutine returned can "
"be awaited to get the earliest next result from the iterable of the "
"remaining awaitables."
msgstr ""

#: ../../library/asyncio-task.rst:865
msgid ""
"Raises :exc:`TimeoutError` if the timeout occurs before all Futures are done."
msgstr ""

#: ../../library/asyncio-task.rst:870
msgid ""
"for coro in as_completed(aws):\n"
"    earliest_result = await coro\n"
"    # ..."
msgstr ""

#: ../../library/asyncio-task.rst:877
msgid ""
"Deprecation warning is emitted if not all awaitable objects in the *aws* "
"iterable are Future-like objects and there is no running event loop."
msgstr ""
"Aviso de descontinuidade é emitido se nem todos os objetos aguardáveis no "
"iterável *aws* forem objetos similar a Futuro, e não existe nenhum laço de "
"eventos em execução."

#: ../../library/asyncio-task.rst:886
msgid "Running in Threads"
msgstr "Executando em Threads"

#: ../../library/asyncio-task.rst:890
msgid "Asynchronously run function *func* in a separate thread."
msgstr "Executa a função *func* assincronamente em uma thread separada."

#: ../../library/asyncio-task.rst:892
msgid ""
"Any \\*args and \\*\\*kwargs supplied for this function are directly passed "
"to *func*. Also, the current :class:`contextvars.Context` is propagated, "
"allowing context variables from the event loop thread to be accessed in the "
"separate thread."
msgstr ""
"Quaisquer \\*args e \\*\\*kwargs fornecidos para esta função são diretamente "
"passados para *func*. Além disso, o :class:`contextvars.Context` atual é "
"propagado, permitindo que variáveis de contexto da thread do laço de eventos "
"sejam acessadas na thread separada."

#: ../../library/asyncio-task.rst:897
msgid ""
"Return a coroutine that can be awaited to get the eventual result of *func*."
msgstr ""
"Retorna uma corrotina que pode ser aguardada para obter o resultado eventual "
"de *func*."

#: ../../library/asyncio-task.rst:899
msgid ""
"This coroutine function is primarily intended to be used for executing IO-"
"bound functions/methods that would otherwise block the event loop if they "
"were run in the main thread. For example::"
msgstr ""

#: ../../library/asyncio-task.rst:903
msgid ""
"def blocking_io():\n"
"    print(f\"start blocking_io at {time.strftime('%X')}\")\n"
"    # Note that time.sleep() can be replaced with any blocking\n"
"    # IO-bound operation, such as file operations.\n"
"    time.sleep(1)\n"
"    print(f\"blocking_io complete at {time.strftime('%X')}\")\n"
"\n"
"async def main():\n"
"    print(f\"started main at {time.strftime('%X')}\")\n"
"\n"
"    await asyncio.gather(\n"
"        asyncio.to_thread(blocking_io),\n"
"        asyncio.sleep(1))\n"
"\n"
"    print(f\"finished main at {time.strftime('%X')}\")\n"
"\n"
"\n"
"asyncio.run(main())\n"
"\n"
"# Expected output:\n"
"#\n"
"# started main at 19:50:53\n"
"# start blocking_io at 19:50:53\n"
"# blocking_io complete at 19:50:54\n"
"# finished main at 19:50:54"
msgstr ""

#: ../../library/asyncio-task.rst:929
msgid ""
"Directly calling ``blocking_io()`` in any coroutine would block the event "
"loop for its duration, resulting in an additional 1 second of run time. "
"Instead, by using ``asyncio.to_thread()``, we can run it in a separate "
"thread without blocking the event loop."
msgstr ""
"Chamar diretamente ``blocking_io()`` em qualquer corrotina iria bloquear o "
"laço de eventos durante a sua duração, resultando em 1 segundo adicional no "
"tempo de execução. Ao invés disso, ao utilizar ``asyncio.to_thread()``, nós "
"podemos executá-la em uma thread separada sem bloquear o laço de eventos."

#: ../../library/asyncio-task.rst:936
msgid ""
"Due to the :term:`GIL`, ``asyncio.to_thread()`` can typically only be used "
"to make IO-bound functions non-blocking. However, for extension modules that "
"release the GIL or alternative Python implementations that don't have one, "
"``asyncio.to_thread()`` can also be used for CPU-bound functions."
msgstr ""
"Devido à :term:`GIL`, ``asyncio.to_thread()`` pode tipicamente ser usado "
"apenas para fazer funções vinculadas a IO não-bloqueantes. Entretanto, para "
"módulos de extensão que liberam o GIL ou implementações alternativas do "
"Python que não tem um, ``asyncio.to_thread()`` também pode ser usado para "
"funções vinculadas à CPU."

#: ../../library/asyncio-task.rst:945
msgid "Scheduling From Other Threads"
msgstr "Agendando a partir de outras Threads"

#: ../../library/asyncio-task.rst:949
msgid "Submit a coroutine to the given event loop.  Thread-safe."
msgstr ""
"Envia uma corrotina para o laço de eventos fornecido. Seguro para thread."

#: ../../library/asyncio-task.rst:951
msgid ""
"Return a :class:`concurrent.futures.Future` to wait for the result from "
"another OS thread."
msgstr ""
"Retorna um :class:`concurrent.futures.Future` para aguardar pelo resultado "
"de outra thread do sistema operacional."

#: ../../library/asyncio-task.rst:954
msgid ""
"This function is meant to be called from a different OS thread than the one "
"where the event loop is running.  Example::"
msgstr ""
"Esta função destina-se a ser chamada partir de uma thread diferente do "
"sistema operacional, da qual o laço de eventos está executando. Exemplo::"

#: ../../library/asyncio-task.rst:957
msgid ""
"# Create a coroutine\n"
"coro = asyncio.sleep(1, result=3)\n"
"\n"
"# Submit the coroutine to a given loop\n"
"future = asyncio.run_coroutine_threadsafe(coro, loop)\n"
"\n"
"# Wait for the result with an optional timeout argument\n"
"assert future.result(timeout) == 3"
msgstr ""

#: ../../library/asyncio-task.rst:966
msgid ""
"If an exception is raised in the coroutine, the returned Future will be "
"notified.  It can also be used to cancel the task in the event loop::"
msgstr ""
"Se uma exceção for levantada na corrotina, o Futuro retornado será "
"notificado. Isso também pode ser usado para cancelar a tarefa no laço de "
"eventos::"

#: ../../library/asyncio-task.rst:970
msgid ""
"try:\n"
"    result = future.result(timeout)\n"
"except TimeoutError:\n"
"    print('The coroutine took too long, cancelling the task...')\n"
"    future.cancel()\n"
"except Exception as exc:\n"
"    print(f'The coroutine raised an exception: {exc!r}')\n"
"else:\n"
"    print(f'The coroutine returned: {result!r}')"
msgstr ""

#: ../../library/asyncio-task.rst:980
msgid ""
"See the :ref:`concurrency and multithreading <asyncio-multithreading>` "
"section of the documentation."
msgstr ""
"Veja a seção :ref:`concorrência e multithreading <asyncio-multithreading>` "
"da documentação."

#: ../../library/asyncio-task.rst:983
msgid ""
"Unlike other asyncio functions this function requires the *loop* argument to "
"be passed explicitly."
msgstr ""
"Ao contrário de outras funções asyncio, esta função requer que o argumento "
"*loop* seja passado explicitamente."

#: ../../library/asyncio-task.rst:990
msgid "Introspection"
msgstr "Introspecção"

#: ../../library/asyncio-task.rst:995
msgid ""
"Return the currently running :class:`Task` instance, or ``None`` if no task "
"is running."
msgstr ""
"Retorna a instância :class:`Task` atualmente em execução, ou ``None`` se "
"nenhuma tarefa estiver executando."

#: ../../library/asyncio-task.rst:998
msgid ""
"If *loop* is ``None`` :func:`get_running_loop` is used to get the current "
"loop."
msgstr ""
"Se *loop* for ``None``, então :func:`get_running_loop` é usado para obter o "
"laço atual."

#: ../../library/asyncio-task.rst:1006
msgid "Return a set of not yet finished :class:`Task` objects run by the loop."
msgstr ""
"Retorna um conjunto de objetos :class:`Task` ainda não concluídos a serem "
"executados pelo laço."

#: ../../library/asyncio-task.rst:1009
msgid ""
"If *loop* is ``None``, :func:`get_running_loop` is used for getting current "
"loop."
msgstr ""
"Se *loop* for ``None``, então :func:`get_running_loop` é usado para obter o "
"laço atual."

#: ../../library/asyncio-task.rst:1017
msgid "Return ``True`` if *obj* is a coroutine object."
msgstr ""

#: ../../library/asyncio-task.rst:1023
msgid "Task Object"
msgstr "Objeto Task"

#: ../../library/asyncio-task.rst:1027
msgid ""
"A :class:`Future-like <Future>` object that runs a Python :ref:`coroutine "
"<coroutine>`.  Not thread-safe."
msgstr ""
"Um objeto :class:`similar a Futuro <Future>` que executa uma :ref:`corrotina "
"<coroutine>` Python. Não é seguro para thread."

#: ../../library/asyncio-task.rst:1030
msgid ""
"Tasks are used to run coroutines in event loops. If a coroutine awaits on a "
"Future, the Task suspends the execution of the coroutine and waits for the "
"completion of the Future.  When the Future is *done*, the execution of the "
"wrapped coroutine resumes."
msgstr ""
"Tarefas são usadas para executar corrotinas em laços de eventos. Se uma "
"corrotina espera por um Futuro, a Tarefa suspende a execução da corrotina e "
"aguarda a conclusão do Futuro. Quando o Futuro é *concluído*, a execução da "
"corrotina contida é retomada."

#: ../../library/asyncio-task.rst:1036
msgid ""
"Event loops use cooperative scheduling: an event loop runs one Task at a "
"time.  While a Task awaits for the completion of a Future, the event loop "
"runs other Tasks, callbacks, or performs IO operations."
msgstr ""
"Laço de eventos usam agendamento cooperativo: um ciclo de evento executa uma "
"Tarefa de cada vez. Enquanto uma Tarefa aguarda a conclusão de um Futuro, o "
"laço de eventos executa outras Tarefas, funções de retorno, ou executa "
"operações de IO."

#: ../../library/asyncio-task.rst:1041
msgid ""
"Use the high-level :func:`asyncio.create_task` function to create Tasks, or "
"the low-level :meth:`loop.create_task` or :func:`ensure_future` functions.  "
"Manual instantiation of Tasks is discouraged."
msgstr ""
"Use a função de alto nível :func:`asyncio.create_task` para criar Tarefas, "
"ou as funções de baixo nível :meth:`loop.create_task` ou :func:"
"`ensure_future`. Instanciação manual de Tarefas é desencorajado."

#: ../../library/asyncio-task.rst:1046
msgid ""
"To cancel a running Task use the :meth:`cancel` method.  Calling it will "
"cause the Task to throw a :exc:`CancelledError` exception into the wrapped "
"coroutine.  If a coroutine is awaiting on a Future object during "
"cancellation, the Future object will be cancelled."
msgstr ""
"Para cancelar uma Tarefa em execução, use o método :meth:`cancel`. Chamar "
"ele fará com que a Tarefa levante uma exceção :exc:`CancelledError` dentro "
"da corrotina contida. Se a corrotina estiver esperando por um objeto Future "
"durante o cancelamento, o objeto Future será cancelado."

#: ../../library/asyncio-task.rst:1051
msgid ""
":meth:`cancelled` can be used to check if the Task was cancelled. The method "
"returns ``True`` if the wrapped coroutine did not suppress the :exc:"
"`CancelledError` exception and was actually cancelled."
msgstr ""
":meth:`cancelled` pode ser usado para verificar se a Tarefa foi cancelada. O "
"método retorna ``True`` se a corrotina envolta não suprimiu a exceção :exc:"
"`CancelledError` e foi na verdade cancelada."

#: ../../library/asyncio-task.rst:1056
msgid ""
":class:`asyncio.Task` inherits from :class:`Future` all of its APIs except :"
"meth:`Future.set_result` and :meth:`Future.set_exception`."
msgstr ""
":class:`asyncio.Task` herda de :class:`Future` todas as suas APIs exceto :"
"meth:`Future.set_result` e :meth:`Future.set_exception`."

#: ../../library/asyncio-task.rst:1060
msgid ""
"An optional keyword-only *context* argument allows specifying a custom :"
"class:`contextvars.Context` for the *coro* to run in. If no *context* is "
"provided, the Task copies the current context and later runs its coroutine "
"in the copied context."
msgstr ""

#: ../../library/asyncio-task.rst:1065
msgid ""
"An optional keyword-only *eager_start* argument allows eagerly starting the "
"execution of the :class:`asyncio.Task` at task creation time. If set to "
"``True`` and the event loop is running, the task will start executing the "
"coroutine immediately, until the first time the coroutine blocks. If the "
"coroutine returns or raises without blocking, the task will be finished "
"eagerly and will skip scheduling to the event loop."
msgstr ""

#: ../../library/asyncio-task.rst:1072
msgid "Added support for the :mod:`contextvars` module."
msgstr "Adicionado suporte para o módulo :mod:`contextvars`."

#: ../../library/asyncio-task.rst:1078
msgid ""
"Deprecation warning is emitted if *loop* is not specified and there is no "
"running event loop."
msgstr ""
"Aviso de descontinuidade é emitido se *loop* não é especificado, e não "
"existe nenhum laço de eventos em execução."

#: ../../library/asyncio-task.rst:1085
msgid "Added the *eager_start* parameter."
msgstr ""

#: ../../library/asyncio-task.rst:1090
msgid "Return ``True`` if the Task is *done*."
msgstr "Retorna ``True`` se a Tarefa estiver *concluída*."

#: ../../library/asyncio-task.rst:1092
msgid ""
"A Task is *done* when the wrapped coroutine either returned a value, raised "
"an exception, or the Task was cancelled."
msgstr ""
"Uma Tarefa está *concluída* quando a corrotina contida retornou um valor, ou "
"levantou uma exceção, ou a Tarefa foi cancelada."

#: ../../library/asyncio-task.rst:1097
msgid "Return the result of the Task."
msgstr "Retorna o resultado da Tarefa."

#: ../../library/asyncio-task.rst:1099
msgid ""
"If the Task is *done*, the result of the wrapped coroutine is returned (or "
"if the coroutine raised an exception, that exception is re-raised.)"
msgstr ""
"Se a Tarefa estiver *concluída*, o resultado da corrotina contida é "
"retornado (ou se a corrotina levantou uma exceção, essa exceção é re-"
"levantada.)"

#: ../../library/asyncio-task.rst:1103 ../../library/asyncio-task.rst:1117
msgid ""
"If the Task has been *cancelled*, this method raises a :exc:`CancelledError` "
"exception."
msgstr ""
"Se a Tarefa foi *cancelada*, este método levanta uma exceção :exc:"
"`CancelledError`."

#: ../../library/asyncio-task.rst:1106
msgid ""
"If the Task's result isn't yet available, this method raises an :exc:"
"`InvalidStateError` exception."
msgstr ""

#: ../../library/asyncio-task.rst:1111
msgid "Return the exception of the Task."
msgstr "Retorna a exceção de uma Tarefa."

#: ../../library/asyncio-task.rst:1113
msgid ""
"If the wrapped coroutine raised an exception that exception is returned.  If "
"the wrapped coroutine returned normally this method returns ``None``."
msgstr ""
"Se a corrotina contida levantou uma exceção, essa exceção é retornada. Se a "
"corrotina contida retornou normalmente, este método retorna ``None``."

#: ../../library/asyncio-task.rst:1120
msgid ""
"If the Task isn't *done* yet, this method raises an :exc:`InvalidStateError` "
"exception."
msgstr ""
"Se a Tarefa não estiver *concluída* ainda, este método levanta uma exceção :"
"exc:`InvalidStateError`."

#: ../../library/asyncio-task.rst:1125
msgid "Add a callback to be run when the Task is *done*."
msgstr ""
"Adiciona uma função de retorno para ser executada quando a Tarefa estiver "
"*concluída*."

#: ../../library/asyncio-task.rst:1127 ../../library/asyncio-task.rst:1136
msgid "This method should only be used in low-level callback-based code."
msgstr ""
"Este método deve ser usado apenas em código de baixo nível baseado em "
"funções de retorno."

#: ../../library/asyncio-task.rst:1129
msgid ""
"See the documentation of :meth:`Future.add_done_callback` for more details."
msgstr ""
"Veja a documentação para :meth:`Future.add_done_callback` para mais detalhes."

#: ../../library/asyncio-task.rst:1134
msgid "Remove *callback* from the callbacks list."
msgstr "Remove *callback* da lista de funções de retorno."

#: ../../library/asyncio-task.rst:1138
msgid ""
"See the documentation of :meth:`Future.remove_done_callback` for more "
"details."
msgstr ""
"Veja a documentação do método :meth:`Future.remove_done_callback` para mais "
"detalhes."

#: ../../library/asyncio-task.rst:1143
msgid "Return the list of stack frames for this Task."
msgstr "Retorna a lista de frames da pilha para esta Tarefa."

#: ../../library/asyncio-task.rst:1145
msgid ""
"If the wrapped coroutine is not done, this returns the stack where it is "
"suspended.  If the coroutine has completed successfully or was cancelled, "
"this returns an empty list. If the coroutine was terminated by an exception, "
"this returns the list of traceback frames."
msgstr ""
"Se a corrotina contida não estiver concluída, isto retorna a pilha onde ela "
"foi suspensa. Se a corrotina foi concluída com sucesso ou foi cancelada, "
"isto retorna uma lista vazia. Se a corrotina foi terminada por uma exceção, "
"isto retorna a lista de frames do traceback (situação da pilha de execução)."

#: ../../library/asyncio-task.rst:1151
msgid "The frames are always ordered from oldest to newest."
msgstr ""
"Os quadros são sempre ordenados dos mais antigos para os mais recentes."

#: ../../library/asyncio-task.rst:1153
msgid "Only one stack frame is returned for a suspended coroutine."
msgstr "Apenas um frame da pilha é retornado para uma corrotina suspensa."

#: ../../library/asyncio-task.rst:1155
msgid ""
"The optional *limit* argument sets the maximum number of frames to return; "
"by default all available frames are returned. The ordering of the returned "
"list differs depending on whether a stack or a traceback is returned: the "
"newest frames of a stack are returned, but the oldest frames of a traceback "
"are returned.  (This matches the behavior of the traceback module.)"
msgstr ""
"O argumento opcional *limit* define o o número de frames máximo para "
"retornar; por padrão todos os frames disponíveis são retornados. O "
"ordenamento da lista retornada é diferente dependendo se uma pilha ou um "
"traceback (situação da pilha de execução) é retornado: os frames mais "
"recentes de uma pilha são retornados, mas os frames mais antigos de um "
"traceback são retornados. (Isso combina com o comportamento do módulo "
"traceback.)"

#: ../../library/asyncio-task.rst:1164
msgid "Print the stack or traceback for this Task."
msgstr "Exibe a pilha ou situação da pilha de execução para esta Tarefa."

#: ../../library/asyncio-task.rst:1166
msgid ""
"This produces output similar to that of the traceback module for the frames "
"retrieved by :meth:`get_stack`."
msgstr ""
"Isto produz uma saída similar a do módulo traceback para frames recuperados "
"por :meth:`get_stack`."

#: ../../library/asyncio-task.rst:1169
msgid "The *limit* argument is passed to :meth:`get_stack` directly."
msgstr "O argumento *limit* é passado para :meth:`get_stack` diretamente."

#: ../../library/asyncio-task.rst:1171
msgid ""
"The *file* argument is an I/O stream to which the output is written; by "
"default output is written to :data:`sys.stdout`."
msgstr ""

#: ../../library/asyncio-task.rst:1176
msgid "Return the coroutine object wrapped by the :class:`Task`."
msgstr "Retorna o objeto corrotina contido pela :class:`Task`."

#: ../../library/asyncio-task.rst:1180
msgid ""
"This will return ``None`` for Tasks which have already completed eagerly. "
"See the :ref:`Eager Task Factory <eager-task-factory>`."
msgstr ""

#: ../../library/asyncio-task.rst:1187
msgid "Newly added eager task execution means result may be ``None``."
msgstr ""

#: ../../library/asyncio-task.rst:1191
msgid ""
"Return the :class:`contextvars.Context` object associated with the task."
msgstr ""

#: ../../library/asyncio-task.rst:1198
msgid "Return the name of the Task."
msgstr "Retorna o nome da Tarefa."

#: ../../library/asyncio-task.rst:1200
msgid ""
"If no name has been explicitly assigned to the Task, the default asyncio "
"Task implementation generates a default name during instantiation."
msgstr ""
"Se nenhum nome foi explicitamente designado para a Tarefa, a implementação "
"padrão asyncio da classe Task gera um nome padrão durante a instanciação."

#: ../../library/asyncio-task.rst:1208
msgid "Set the name of the Task."
msgstr "Define o nome da Tarefa."

#: ../../library/asyncio-task.rst:1210
msgid ""
"The *value* argument can be any object, which is then converted to a string."
msgstr ""
"O argumento *value* pode ser qualquer objeto, o qual é então convertido para "
"uma string."

#: ../../library/asyncio-task.rst:1213
msgid ""
"In the default Task implementation, the name will be visible in the :func:"
"`repr` output of a task object."
msgstr ""
"Na implementação padrão da Tarefa, o nome será visível na :func:`repr` de "
"saída de um objeto task."

#: ../../library/asyncio-task.rst:1220
msgid "Request the Task to be cancelled."
msgstr "Solicita o cancelamento da Tarefa."

#: ../../library/asyncio-task.rst:1222
msgid ""
"This arranges for a :exc:`CancelledError` exception to be thrown into the "
"wrapped coroutine on the next cycle of the event loop."
msgstr ""
"Isto prepara para uma exceção :exc:`CancelledError` ser lançada na corrotina "
"contida no próximo ciclo do laço de eventos."

#: ../../library/asyncio-task.rst:1225
msgid ""
"The coroutine then has a chance to clean up or even deny the request by "
"suppressing the exception with a :keyword:`try` ... ... ``except "
"CancelledError`` ... :keyword:`finally` block. Therefore, unlike :meth:"
"`Future.cancel`, :meth:`Task.cancel` does not guarantee that the Task will "
"be cancelled, although suppressing cancellation completely is not common and "
"is actively discouraged.  Should the coroutine nevertheless decide to "
"suppress the cancellation, it needs to call :meth:`Task.uncancel` in "
"addition to catching the exception."
msgstr ""

#: ../../library/asyncio-task.rst:1235
msgid "Added the *msg* parameter."
msgstr "Adicionado o  parâmetro *msg*."

#: ../../library/asyncio-task.rst:1238
msgid "The ``msg`` parameter is propagated from cancelled task to its awaiter."
msgstr ""

#: ../../library/asyncio-task.rst:1243
msgid ""
"The following example illustrates how coroutines can intercept the "
"cancellation request::"
msgstr ""
"O seguinte exemplo ilustra como corrotinas podem interceptar o cancelamento "
"de requisições::"

#: ../../library/asyncio-task.rst:1246
msgid ""
"async def cancel_me():\n"
"    print('cancel_me(): before sleep')\n"
"\n"
"    try:\n"
"        # Wait for 1 hour\n"
"        await asyncio.sleep(3600)\n"
"    except asyncio.CancelledError:\n"
"        print('cancel_me(): cancel sleep')\n"
"        raise\n"
"    finally:\n"
"        print('cancel_me(): after sleep')\n"
"\n"
"async def main():\n"
"    # Create a \"cancel_me\" Task\n"
"    task = asyncio.create_task(cancel_me())\n"
"\n"
"    # Wait for 1 second\n"
"    await asyncio.sleep(1)\n"
"\n"
"    task.cancel()\n"
"    try:\n"
"        await task\n"
"    except asyncio.CancelledError:\n"
"        print(\"main(): cancel_me is cancelled now\")\n"
"\n"
"asyncio.run(main())\n"
"\n"
"# Expected output:\n"
"#\n"
"#     cancel_me(): before sleep\n"
"#     cancel_me(): cancel sleep\n"
"#     cancel_me(): after sleep\n"
"#     main(): cancel_me is cancelled now"
msgstr ""

#: ../../library/asyncio-task.rst:1282
msgid "Return ``True`` if the Task is *cancelled*."
msgstr "Retorna ``True`` se a Tarefa for *cancelada*."

#: ../../library/asyncio-task.rst:1284
msgid ""
"The Task is *cancelled* when the cancellation was requested with :meth:"
"`cancel` and the wrapped coroutine propagated the :exc:`CancelledError` "
"exception thrown into it."
msgstr ""
"A Tarefa é *cancelada* quando o cancelamento foi requisitado com :meth:"
"`cancel` e a corrotina contida propagou a exceção :exc:`CancelledError` "
"gerada nela."

#: ../../library/asyncio-task.rst:1290
msgid "Decrement the count of cancellation requests to this Task."
msgstr ""

#: ../../library/asyncio-task.rst:1292
msgid "Returns the remaining number of cancellation requests."
msgstr ""

#: ../../library/asyncio-task.rst:1294
msgid ""
"Note that once execution of a cancelled task completed, further calls to :"
"meth:`uncancel` are ineffective."
msgstr ""

#: ../../library/asyncio-task.rst:1299
msgid ""
"This method is used by asyncio's internals and isn't expected to be used by "
"end-user code.  In particular, if a Task gets successfully uncancelled, this "
"allows for elements of structured concurrency like :ref:`taskgroups` and :"
"func:`asyncio.timeout` to continue running, isolating cancellation to the "
"respective structured block. For example::"
msgstr ""

#: ../../library/asyncio-task.rst:1306
msgid ""
"async def make_request_with_timeout():\n"
"    try:\n"
"        async with asyncio.timeout(1):\n"
"            # Structured block affected by the timeout:\n"
"            await make_request()\n"
"            await make_another_request()\n"
"    except TimeoutError:\n"
"        log(\"There was a timeout\")\n"
"    # Outer code not affected by the timeout:\n"
"    await unrelated_code()"
msgstr ""

#: ../../library/asyncio-task.rst:1317
msgid ""
"While the block with ``make_request()`` and ``make_another_request()`` might "
"get cancelled due to the timeout, ``unrelated_code()`` should continue "
"running even in case of the timeout.  This is implemented with :meth:"
"`uncancel`.  :class:`TaskGroup` context managers use :func:`uncancel` in a "
"similar fashion."
msgstr ""

#: ../../library/asyncio-task.rst:1323
msgid ""
"If end-user code is, for some reason, suppressing cancellation by catching :"
"exc:`CancelledError`, it needs to call this method to remove the "
"cancellation state."
msgstr ""

#: ../../library/asyncio-task.rst:1329
msgid ""
"Return the number of pending cancellation requests to this Task, i.e., the "
"number of calls to :meth:`cancel` less the number of :meth:`uncancel` calls."
msgstr ""

#: ../../library/asyncio-task.rst:1333
msgid ""
"Note that if this number is greater than zero but the Task is still "
"executing, :meth:`cancelled` will still return ``False``. This is because "
"this number can be lowered by calling :meth:`uncancel`, which can lead to "
"the task not being cancelled after all if the cancellation requests go down "
"to zero."
msgstr ""

#: ../../library/asyncio-task.rst:1339
msgid ""
"This method is used by asyncio's internals and isn't expected to be used by "
"end-user code.  See :meth:`uncancel` for more details."
msgstr ""
