# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2025, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# Leticia Portella <leportella@gmail.com>, 2024
# Rafael Fontenelle <rffontenelle@gmail.com>, 2024
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.13\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-01-03 14:16+0000\n"
"PO-Revision-Date: 2021-06-28 00:54+0000\n"
"Last-Translator: Rafael Fontenelle <rffontenelle@gmail.com>, 2024\n"
"Language-Team: Portuguese (Brazil) (https://app.transifex.com/python-doc/"
"teams/5390/pt_BR/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt_BR\n"
"Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % "
"1000000 == 0 ? 1 : 2;\n"

#: ../../library/asyncio-exceptions.rst:8
msgid "Exceptions"
msgstr "Exceções"

#: ../../library/asyncio-exceptions.rst:10
msgid "**Source code:** :source:`Lib/asyncio/exceptions.py`"
msgstr "**Código-fonte:** :source:`Lib/asyncio/exceptions.py`"

#: ../../library/asyncio-exceptions.rst:16
msgid ""
"A deprecated alias of :exc:`TimeoutError`, raised when the operation has "
"exceeded the given deadline."
msgstr ""
"Um apelido descontinuado de :exc:`TimeoutError`, levantado quando a operação "
"excedeu o prazo determinado."

#: ../../library/asyncio-exceptions.rst:21
msgid "This class was made an alias of :exc:`TimeoutError`."
msgstr "Esta classe foi feita como um apelido de :exc:`TimeoutError`."

#: ../../library/asyncio-exceptions.rst:26
msgid "The operation has been cancelled."
msgstr "A operação foi cancelada."

#: ../../library/asyncio-exceptions.rst:28
msgid ""
"This exception can be caught to perform custom operations when asyncio Tasks "
"are cancelled.  In almost all situations the exception must be re-raised."
msgstr ""
"Esta exceção pode ser capturada para executar operações personalizadas "
"quando as tarefas assíncronas são canceladas. Em quase todas as situações, a "
"exceção deve ser levantada novamente."

#: ../../library/asyncio-exceptions.rst:34
msgid ""
":exc:`CancelledError` is now a subclass of :class:`BaseException` rather "
"than :class:`Exception`."
msgstr ""
":exc:`CancelledError` é agora uma subclasse de :class:`BaseException` em vez "
"de :class:`Exception`."

#: ../../library/asyncio-exceptions.rst:39
msgid "Invalid internal state of :class:`Task` or :class:`Future`."
msgstr "Estado interno inválido de :class:`Task` ou :class:`Future`."

#: ../../library/asyncio-exceptions.rst:41
msgid ""
"Can be raised in situations like setting a result value for a *Future* "
"object that already has a result value set."
msgstr ""
"Pode ser levantada em situações como definir um valor de resultado para um "
"objeto *Future* que já tem um valor de resultado definido."

#: ../../library/asyncio-exceptions.rst:47
msgid ""
"The \"sendfile\" syscall is not available for the given socket or file type."
msgstr ""
"A *syscall* \"sendfile\" não está disponível para o soquete ou tipo de "
"arquivo fornecido."

#: ../../library/asyncio-exceptions.rst:50
msgid "A subclass of :exc:`RuntimeError`."
msgstr "Uma subclasse de :exc:`RuntimeError`."

#: ../../library/asyncio-exceptions.rst:55
msgid "The requested read operation did not complete fully."
msgstr "A operação de leitura solicitada não foi totalmente concluída."

#: ../../library/asyncio-exceptions.rst:57
msgid "Raised by the :ref:`asyncio stream APIs<asyncio-streams>`."
msgstr "Levantada pelas :ref:`APIs de fluxo de asyncio<asyncio-streams>`."

#: ../../library/asyncio-exceptions.rst:59
msgid "This exception is a subclass of :exc:`EOFError`."
msgstr "Esta exceção é uma subclasse de :exc:`EOFError`."

#: ../../library/asyncio-exceptions.rst:63
msgid "The total number (:class:`int`) of expected bytes."
msgstr "O número total (:class:`int`) de bytes esperados."

#: ../../library/asyncio-exceptions.rst:67
msgid "A string of :class:`bytes` read before the end of stream was reached."
msgstr ""
"Uma string de :class:`bytes` lida antes do final do fluxo ser alcançado."

#: ../../library/asyncio-exceptions.rst:72
msgid "Reached the buffer size limit while looking for a separator."
msgstr "Atingiu o limite de tamanho do buffer ao procurar um separador."

#: ../../library/asyncio-exceptions.rst:74
msgid "Raised by the :ref:`asyncio stream APIs <asyncio-streams>`."
msgstr "Levantada pelas :ref:`APIs de fluxo de asyncio <asyncio-streams>`."

#: ../../library/asyncio-exceptions.rst:78
msgid "The total number of to be consumed bytes."
msgstr "O número total de bytes a serem consumidos."
