# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2024, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# Rafael Fontenelle <rffontenelle@gmail.com>, 2024
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.12\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-11-12 09:11+0000\n"
"PO-Revision-Date: 2024-05-11 00:33+0000\n"
"Last-Translator: Rafael Fontenelle <rffontenelle@gmail.com>, 2024\n"
"Language-Team: Portuguese (Brazil) (https://app.transifex.com/python-doc/"
"teams/5390/pt_BR/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: pt_BR\n"
"Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % "
"1000000 == 0 ? 1 : 2;\n"

#: ../../library/exceptions.rst:4
msgid "Built-in Exceptions"
msgstr "Exceções embutidas"

#: ../../library/exceptions.rst:10
msgid ""
"In Python, all exceptions must be instances of a class that derives from :"
"class:`BaseException`.  In a :keyword:`try` statement with an :keyword:"
"`except` clause that mentions a particular class, that clause also handles "
"any exception classes derived from that class (but not exception classes "
"from which *it* is derived).  Two exception classes that are not related via "
"subclassing are never equivalent, even if they have the same name."
msgstr ""
"No Python, todas as exceções devem ser instâncias de uma classe derivada de :"
"class:`BaseException`. Em uma instrução :keyword:`try` com uma cláusula :"
"keyword:`except` que menciona uma classe específica, essa cláusula também "
"lida com qualquer classe de exceção derivada dessa classe (mas não com as "
"classes de exceção a partir das quais *ela* é derivada). Duas classes de "
"exceção que não são relacionadas por subclasse nunca são equivalentes, mesmo "
"que tenham o mesmo nome."

#: ../../library/exceptions.rst:19
msgid ""
"The built-in exceptions listed in this chapter can be generated by the "
"interpreter or built-in functions.  Except where mentioned, they have an "
"\"associated value\" indicating the detailed cause of the error.  This may "
"be a string or a tuple of several items of information (e.g., an error code "
"and a string explaining the code).  The associated value is usually passed "
"as arguments to the exception class's constructor."
msgstr ""
"As exceções embutidas listadas neste capítulo podem ser geradas pelo "
"interpretador ou pelas funções embutidas. Exceto onde mencionado, eles têm "
"um \"valor associado\" indicando a causa detalhada do erro. Pode ser uma "
"string ou uma tupla de vários itens de informação (por exemplo, um código de "
"erro e uma string que explica o código). O valor associado geralmente é "
"passado como argumentos para o construtor da classe de exceção."

#: ../../library/exceptions.rst:26
msgid ""
"User code can raise built-in exceptions.  This can be used to test an "
"exception handler or to report an error condition \"just like\" the "
"situation in which the interpreter raises the same exception; but beware "
"that there is nothing to prevent user code from raising an inappropriate "
"error."
msgstr ""
"O código do usuário pode gerar exceções embutidas. Isso pode ser usado para "
"testar um manipulador de exceções ou para relatar uma condição de erro "
"\"exatamente como\" a situação na qual o interpretador gera a mesma exceção; "
"mas lembre-se de que nada impede o código do usuário de gerar um erro "
"inadequado."

#: ../../library/exceptions.rst:31
msgid ""
"The built-in exception classes can be subclassed to define new exceptions; "
"programmers are encouraged to derive new exceptions from the :exc:"
"`Exception` class or one of its subclasses, and not from :exc:"
"`BaseException`.  More information on defining exceptions is available in "
"the Python Tutorial under :ref:`tut-userexceptions`."
msgstr ""
"As classes de exceções embutidas podem ser usadas como subclasses para "
"definir novas exceções; Os programadores são incentivados a derivar novas "
"exceções da classe :exc:`Exception` ou de uma de suas subclasses, e não de :"
"exc:`BaseException`. Mais informações sobre a definição de exceções estão "
"disponíveis no Tutorial do Python em :ref:`tut-userexceptions`."

#: ../../library/exceptions.rst:39
msgid "Exception context"
msgstr "Contexto da exceção"

#: ../../library/exceptions.rst:46
msgid ""
"Three attributes on exception objects provide information about the context "
"in which the exception was raised:"
msgstr ""
"Três atributos em objetos exceções fornecem informações sobre o contexto em "
"que a exceção foi levantada."

#: ../../library/exceptions.rst:53
msgid ""
"When raising a new exception while another exception is already being "
"handled, the new exception's :attr:`!__context__` attribute is automatically "
"set to the handled exception.  An exception may be handled when an :keyword:"
"`except` or :keyword:`finally` clause, or a :keyword:`with` statement, is "
"used."
msgstr ""
"Ao levantar uma nova exceção enquanto outra exceção já está sendo tratada, o "
"atributo :attr:`!__context__` da nova exceção é automaticamente definido "
"para a exceção tratada. Uma exceção pode ser tratada quando uma cláusula :"
"keyword:`except` ou :keyword:`finally`, ou uma instrução :keyword:`with`, é "
"usada."

#: ../../library/exceptions.rst:59
msgid ""
"This implicit exception context can be supplemented with an explicit cause "
"by using :keyword:`!from` with :keyword:`raise`::"
msgstr ""
"Esse contexto implícito da exceção pode ser complementado com uma causa "
"explícita usando :keyword:`!from` com :keyword:`raise`::"

#: ../../library/exceptions.rst:63
msgid "raise new_exc from original_exc"
msgstr "raise new_exc from original_exc"

#: ../../library/exceptions.rst:65
msgid ""
"The expression following :keyword:`from<raise>` must be an exception or "
"``None``. It will be set as :attr:`!__cause__` on the raised exception. "
"Setting :attr:`!__cause__` also implicitly sets the :attr:`!"
"__suppress_context__` attribute to ``True``, so that using ``raise new_exc "
"from None`` effectively replaces the old exception with the new one for "
"display purposes (e.g. converting :exc:`KeyError` to :exc:`AttributeError`), "
"while leaving the old exception available in :attr:`!__context__` for "
"introspection when debugging."
msgstr ""
"A expressão a seguir :keyword:`from<raise>` deve ser uma exceção ou "
"``None``. Ela será definida como :attr:`!__cause__` na exceção levantada. A "
"definição de :attr:`!__cause__` também define implicitamente o atributo :"
"attr:`!__suppress_context__` como ``True``, de modo que o uso de ``raise "
"new_exc from None`` substitui efetivamente a exceção antiga pela nova para "
"fins de exibição (por exemplo, convertendo :exc:`KeyError` para :exc:"
"`AttributeError`), deixando a exceção antiga disponível em :attr:`!"
"__context__` para introspecção durante a depuração."

#: ../../library/exceptions.rst:74
msgid ""
"The default traceback display code shows these chained exceptions in "
"addition to the traceback for the exception itself. An explicitly chained "
"exception in :attr:`!__cause__` is always shown when present. An implicitly "
"chained exception in :attr:`!__context__` is shown only if :attr:`!"
"__cause__` is :const:`None` and :attr:`!__suppress_context__` is false."
msgstr ""
"O código de exibição padrão do traceback mostra essas exceções encadeadas, "
"além do traceback da própria exceção. Uma exceção explicitamente encadeada "
"em :attr:`!__cause__` sempre é mostrada quando presente. Uma exceção "
"implicitamente encadeada em :attr:`!__context__` é mostrada apenas se :attr:"
"`!__cause__` for :const:`None` e :attr:`!__suppress_context__` for falso."

#: ../../library/exceptions.rst:80
msgid ""
"In either case, the exception itself is always shown after any chained "
"exceptions so that the final line of the traceback always shows the last "
"exception that was raised."
msgstr ""
"Em qualquer um dos casos, a exceção em si sempre é mostrada após todas as "
"exceções encadeadas, de modo que a linha final do traceback sempre mostre a "
"última exceção que foi levantada."

#: ../../library/exceptions.rst:86
msgid "Inheriting from built-in exceptions"
msgstr "Herdando de exceções embutidas"

#: ../../library/exceptions.rst:88
msgid ""
"User code can create subclasses that inherit from an exception type. It's "
"recommended to only subclass one exception type at a time to avoid any "
"possible conflicts between how the bases handle the ``args`` attribute, as "
"well as due to possible memory layout incompatibilities."
msgstr ""
"O código do usuário pode criar subclasses que herdam de um tipo de exceção. "
"É recomendado criar subclasse de apenas um tipo de exceção por vez para "
"evitar possíveis conflitos entre como as bases tratam o atributo ``args``, "
"bem como devido a possíveis incompatibilidades de layout de memória."

#: ../../library/exceptions.rst:95
msgid ""
"Most built-in exceptions are implemented in C for efficiency, see: :source:"
"`Objects/exceptions.c`.  Some have custom memory layouts which makes it "
"impossible to create a subclass that inherits from multiple exception types. "
"The memory layout of a type is an implementation detail and might change "
"between Python versions, leading to new conflicts in the future.  Therefore, "
"it's recommended to avoid subclassing multiple exception types altogether."
msgstr ""
"A maioria das exceções embutidas são implementadas em C para eficiência, "
"veja: :source:`Objects/exceptions.c`. Algumas têm layouts de memória "
"personalizados, o que impossibilita a criação de uma subclasse que herda de "
"vários tipos de exceção. O layout de memória de um tipo é um detalhe de "
"implementação e pode mudar entre as versões do Python, levando a novos "
"conflitos no futuro. Portanto, é recomendável evitar criar subclasses de "
"vários tipos de exceção."

#: ../../library/exceptions.rst:105
msgid "Base classes"
msgstr "Classes base"

#: ../../library/exceptions.rst:107
msgid ""
"The following exceptions are used mostly as base classes for other "
"exceptions."
msgstr ""
"As seguintes exceções são usadas principalmente como classes base para "
"outras exceções."

#: ../../library/exceptions.rst:111
msgid ""
"The base class for all built-in exceptions.  It is not meant to be directly "
"inherited by user-defined classes (for that, use :exc:`Exception`).  If :"
"func:`str` is called on an instance of this class, the representation of the "
"argument(s) to the instance are returned, or the empty string when there "
"were no arguments."
msgstr ""
"A classe base para todas as exceções embutidas. Não é para ser herdada "
"diretamente por classes definidas pelo usuário (para isso, use :exc:"
"`Exception`). Se :func:`str` for chamado em uma instância desta classe, a "
"representação do(s) argumento(s) para a instância será retornada ou a string "
"vazia quando não houver argumentos."

#: ../../library/exceptions.rst:119
msgid ""
"The tuple of arguments given to the exception constructor.  Some built-in "
"exceptions (like :exc:`OSError`) expect a certain number of arguments and "
"assign a special meaning to the elements of this tuple, while others are "
"usually called only with a single string giving an error message."
msgstr ""
"A tupla de argumentos fornecidos ao construtor de exceções. Algumas exceções "
"embutidas (como :exc:`OSError`) esperam um certo número de argumentos e "
"atribuem um significado especial aos elementos dessa tupla, enquanto outras "
"são normalmente chamadas apenas com uma única string que fornece uma "
"mensagem de erro."

#: ../../library/exceptions.rst:126
msgid ""
"This method sets *tb* as the new traceback for the exception and returns the "
"exception object.  It was more commonly used before the exception chaining "
"features of :pep:`3134` became available.  The following example shows how "
"we can convert an instance of ``SomeException`` into an instance of "
"``OtherException`` while preserving the traceback.  Once raised, the current "
"frame is pushed onto the traceback of the ``OtherException``, as would have "
"happened to the traceback of the original ``SomeException`` had we allowed "
"it to propagate to the caller. ::"
msgstr ""
"Este método define *tb* como o novo traceback (situação da pilha de "
"execução) para a exceção e retorna o objeto exceção. Era mais comumente "
"usado antes que os recursos de encadeamento de exceções de :pep:`3134` se "
"tornassem disponíveis. O exemplo a seguir mostra como podemos converter uma "
"instância de ``SomeException`` em uma instância de ``OtherException`` "
"enquanto preservamos o traceback. Uma vez gerado, o quadro atual é empurrado "
"para o traceback de ``OtherException``, como teria acontecido com o "
"traceback de ``SomeException`` original se tivéssemos permitido que ele se "
"propagasse para o chamador. ::"

#: ../../library/exceptions.rst:135
msgid ""
"try:\n"
"    ...\n"
"except SomeException:\n"
"    tb = sys.exception().__traceback__\n"
"    raise OtherException(...).with_traceback(tb)"
msgstr ""
"try:\n"
"    ...\n"
"except SomeException:\n"
"    tb = sys.exception().__traceback__\n"
"    raise OtherException(...).with_traceback(tb)"

#: ../../library/exceptions.rst:143
msgid ""
"A writable field that holds the :ref:`traceback object <traceback-objects>` "
"associated with this exception. See also: :ref:`raise`."
msgstr ""
"Um campo gravável que contém o :ref:`objeto traceback <traceback-objects>` "
"associado a esta exceção. Veja também: :ref:`raise`."

#: ../../library/exceptions.rst:149
msgid ""
"Add the string ``note`` to the exception's notes which appear in the "
"standard traceback after the exception string. A :exc:`TypeError` is raised "
"if ``note`` is not a string."
msgstr ""
"Adiciona a string ``note`` às notas da exceção que aparecem no traceback "
"padrão após a string de exceção. Uma exceção :exc:`TypeError` é levantada se "
"``note`` não for uma string."

#: ../../library/exceptions.rst:157
msgid ""
"A list of the notes of this exception, which were added with :meth:"
"`add_note`. This attribute is created when :meth:`add_note` is called."
msgstr ""
"Uma lista das notas desta exceção, que foram adicionadas com :meth:"
"`add_note`. Este atributo é criado quando :meth:`add_note` é chamado."

#: ../../library/exceptions.rst:165
msgid ""
"All built-in, non-system-exiting exceptions are derived from this class.  "
"All user-defined exceptions should also be derived from this class."
msgstr ""
"Todas as exceções embutidas que não saem para o sistema são derivadas dessa "
"classe. Todas as exceções definidas pelo usuário também devem ser derivadas "
"dessa classe."

#: ../../library/exceptions.rst:171
msgid ""
"The base class for those built-in exceptions that are raised for various "
"arithmetic errors: :exc:`OverflowError`, :exc:`ZeroDivisionError`, :exc:"
"`FloatingPointError`."
msgstr ""
"A classe base para as exceções embutidas levantadas para vários erros "
"aritméticos: :exc:`OverflowError`, :exc:`ZeroDivisionError`, :exc:"
"`FloatingPointError`."

#: ../../library/exceptions.rst:178
msgid ""
"Raised when a :ref:`buffer <bufferobjects>` related operation cannot be "
"performed."
msgstr ""
"Levantado quando uma operação relacionada a :ref:`buffer <bufferobjects>` "
"não puder ser realizada."

#: ../../library/exceptions.rst:184
msgid ""
"The base class for the exceptions that are raised when a key or index used "
"on a mapping or sequence is invalid: :exc:`IndexError`, :exc:`KeyError`.  "
"This can be raised directly by :func:`codecs.lookup`."
msgstr ""
"A classe base para as exceções levantadas quando uma chave ou índice usado "
"em um mapeamento ou sequência é inválido: :exc:`IndexError`, :exc:"
"`KeyError`. Isso pode ser levantado diretamente por :func:`codecs.lookup`."

#: ../../library/exceptions.rst:190
msgid "Concrete exceptions"
msgstr "Exceções concretas"

#: ../../library/exceptions.rst:192
msgid "The following exceptions are the exceptions that are usually raised."
msgstr "As seguintes exceções são as que geralmente são levantados."

#: ../../library/exceptions.rst:198
msgid "Raised when an :keyword:`assert` statement fails."
msgstr "Levantado quando uma instrução :keyword:`assert` falha."

#: ../../library/exceptions.rst:203
msgid ""
"Raised when an attribute reference (see :ref:`attribute-references`) or "
"assignment fails.  (When an object does not support attribute references or "
"attribute assignments at all, :exc:`TypeError` is raised.)"
msgstr ""
"Levantado quando uma referência de atributo (consulte :ref:`attribute-"
"references`) ou atribuição falha. (Quando um objeto não oferece suporte a "
"referências ou atribuições de atributos, :exc:`TypeError` é levantado.)"

#: ../../library/exceptions.rst:207
msgid ""
"The :attr:`name` and :attr:`obj` attributes can be set using keyword-only "
"arguments to the constructor. When set they represent the name of the "
"attribute that was attempted to be accessed and the object that was accessed "
"for said attribute, respectively."
msgstr ""
"Os atributos :attr:`name` e :attr:`obj` podem ser configurados usando "
"argumentos somente-nomeados para o construtor. Quando configurados, eles "
"representam o nome do atributo que se tentou acessar e do objeto que foi "
"acessado por esse atributo, respectivamente."

#: ../../library/exceptions.rst:212
msgid "Added the :attr:`name` and :attr:`obj` attributes."
msgstr "Adicionado os atributos :attr:`name` e :attr:`obj`."

#: ../../library/exceptions.rst:217
msgid ""
"Raised when the :func:`input` function hits an end-of-file condition (EOF) "
"without reading any data. (N.B.: the :meth:`io.IOBase.read` and :meth:`io."
"IOBase.readline` methods return an empty string when they hit EOF.)"
msgstr ""
"Levantado quando a função :func:`input` atinge uma condição de fim de "
"arquivo (EOF) sem ler nenhum dado. (Note: os métodos :meth:`io.IOBase.read` "
"e :meth:`io.IOBase.readline` retornam uma string vazia quando pressionam o "
"EOF.)"

#: ../../library/exceptions.rst:224
msgid "Not currently used."
msgstr "Não usado atualmente."

#: ../../library/exceptions.rst:229
msgid ""
"Raised when a :term:`generator` or :term:`coroutine` is closed; see :meth:"
"`generator.close` and :meth:`coroutine.close`.  It directly inherits from :"
"exc:`BaseException` instead of :exc:`Exception` since it is technically not "
"an error."
msgstr ""
"Levantado quando um :term:`gerador` ou uma :term:`corrotina` está "
"fechado(a); veja :meth:`generator.close` e :meth:`coroutine.close`. Herda "
"diretamente de :exc:`BaseException` em vez de :exc:`Exception`, já que "
"tecnicamente não é um erro."

#: ../../library/exceptions.rst:237
msgid ""
"Raised when the :keyword:`import` statement has troubles trying to load a "
"module.  Also raised when the \"from list\" in ``from ... import`` has a "
"name that cannot be found."
msgstr ""
"Levantada quando a instrução :keyword:`import` tem problemas ao tentar "
"carregar um módulo. Também é gerado quando o \"from list\" em ``from ... "
"import`` tem um nome que não pode ser encontrado."

#: ../../library/exceptions.rst:241
msgid ""
"The optional *name* and *path* keyword-only arguments set the corresponding "
"attributes:"
msgstr ""
"O argumentos somente-nomeados opcionais *name* e o *path* definem o "
"atributos correspondente:"

#: ../../library/exceptions.rst:246
msgid "The name of the module that was attempted to be imported."
msgstr "O nome do módulo que tentou-se fazer a importação."

#: ../../library/exceptions.rst:250
msgid "The path to any file which triggered the exception."
msgstr "O caminho para qualquer arquivo que acionou a exceção."

#: ../../library/exceptions.rst:252
msgid "Added the :attr:`name` and :attr:`path` attributes."
msgstr "Adicionados os atributos :attr:`name` e :attr:`path`."

#: ../../library/exceptions.rst:257
msgid ""
"A subclass of :exc:`ImportError` which is raised by :keyword:`import` when a "
"module could not be located.  It is also raised when ``None`` is found in :"
"data:`sys.modules`."
msgstr ""
"Uma subclasse de :exc:`ImportError` que é levantada por :keyword:`import` "
"quando um módulo não pôde ser localizado. Também é levantada quando ``None`` "
"é encontrado em :data:`sys.modules`."

#: ../../library/exceptions.rst:266
msgid ""
"Raised when a sequence subscript is out of range.  (Slice indices are "
"silently truncated to fall in the allowed range; if an index is not an "
"integer, :exc:`TypeError` is raised.)"
msgstr ""
"Levantada quando um índice de alguma sequência está fora do intervalo.  "
"(Índices de fatia são truncados silenciosamente para cair num intervalo "
"permitido; se um índice não for um inteiro, :exc:`TypeError` é levantada.)"

#: ../../library/exceptions.rst:275
msgid ""
"Raised when a mapping (dictionary) key is not found in the set of existing "
"keys."
msgstr ""
"Levantada quando uma chave de mapeamento (dicionário) não é encontrada no "
"conjunto de chaves existentes."

#: ../../library/exceptions.rst:282
msgid ""
"Raised when the user hits the interrupt key (normally :kbd:`Control-C` or :"
"kbd:`Delete`).  During execution, a check for interrupts is made regularly. "
"The exception inherits from :exc:`BaseException` so as to not be "
"accidentally caught by code that catches :exc:`Exception` and thus prevent "
"the interpreter from exiting."
msgstr ""
"Levantada quando um usuário aperta a tecla de interrupção (normalmente :kbd:"
"`Control-C` ou :kbd:`Delete`).  Durante a execução, uma checagem de "
"interrupção é feita regularmente. A exceção herda de :exc:`BaseException` "
"para que não seja capturada acidentalmente por códigos que tratam :exc:"
"`Exception` e assim evita que o interpretador saia."

#: ../../library/exceptions.rst:290
msgid ""
"Catching a :exc:`KeyboardInterrupt` requires special consideration. Because "
"it can be raised at unpredictable points, it may, in some circumstances, "
"leave the running program in an inconsistent state. It is generally best to "
"allow :exc:`KeyboardInterrupt` to end the program as quickly as possible or "
"avoid raising it entirely. (See :ref:`handlers-and-exceptions`.)"
msgstr ""
"Capturar uma :exc:`KeyboardInterrupt` requer consideração especial. Como "
"pode ser levantada em pontos imprevisíveis, pode, em algumas circunstâncias, "
"deixar o programa em execução em um estado inconsistente. Geralmente é "
"melhor permitir que :exc:`KeyboardInterrupt` termine o programa o mais "
"rápido possível ou evitar levantá-la de todo. (Veja :ref:`handlers-and-"
"exceptions`.)"

#: ../../library/exceptions.rst:300
msgid ""
"Raised when an operation runs out of memory but the situation may still be "
"rescued (by deleting some objects).  The associated value is a string "
"indicating what kind of (internal) operation ran out of memory. Note that "
"because of the underlying memory management architecture (C's :c:func:"
"`malloc` function), the interpreter may not always be able to completely "
"recover from this situation; it nevertheless raises an exception so that a "
"stack traceback can be printed, in case a run-away program was the cause."
msgstr ""
"Levantada quando uma operação fica sem memória mas a situação ainda pode ser "
"recuperada (excluindo alguns objetos).  O valor associado é uma string que "
"indica o tipo de operação (interna) que ficou sem memória. Observe que, por "
"causa da arquitetura de gerenciamento de memória subjacente (função :c:func:"
"`malloc` do C), o interpretador pode não ser capaz de se recuperar "
"completamente da situação; no entanto, levanta uma exceção para que um "
"traceback possa ser impresso, no caso de um outro programa ser a causa."

#: ../../library/exceptions.rst:311
msgid ""
"Raised when a local or global name is not found.  This applies only to "
"unqualified names.  The associated value is an error message that includes "
"the name that could not be found."
msgstr ""
"Levantada quando um nome local ou global não é encontrado. Isso se aplica "
"apenas a nomes não qualificados. O valor associado é uma mensagem de erro "
"que inclui o nome que não pode ser encontrado."

#: ../../library/exceptions.rst:315
msgid ""
"The :attr:`name` attribute can be set using a keyword-only argument to the "
"constructor. When set it represent the name of the variable that was "
"attempted to be accessed."
msgstr ""
"O atributo :attr:`name` pode ser definido usando um argumento somente-"
"nomeado para o construtor. Quando definido, representa o nome da variável "
"que foi tentada ser acessada."

#: ../../library/exceptions.rst:319
msgid "Added the :attr:`name` attribute."
msgstr "Adicionado o atributo :attr:`name`."

#: ../../library/exceptions.rst:325
msgid ""
"This exception is derived from :exc:`RuntimeError`.  In user defined base "
"classes, abstract methods should raise this exception when they require "
"derived classes to override the method, or while the class is being "
"developed to indicate that the real implementation still needs to be added."
msgstr ""
"Essa exceção é derivada da :exc:`RuntimeError`.  Em classes base, definidas "
"pelo usuário, os métodos abstratos devem gerar essa exceção quando requerem "
"que classes derivadas substituam o método, ou enquanto a classe está sendo "
"desenvolvida, para indicar que a implementação real ainda precisa ser "
"adicionada."

#: ../../library/exceptions.rst:332
msgid ""
"It should not be used to indicate that an operator or method is not meant to "
"be supported at all -- in that case either leave the operator / method "
"undefined or, if a subclass, set it to :data:`None`."
msgstr ""
"Não deve ser usada para indicar que um operador ou método não será mais "
"suportado -- nesse caso deixe o operador / método indefinido ou, se é uma "
"subclasse, defina-o como :data:`None`."

#: ../../library/exceptions.rst:338
msgid ""
"``NotImplementedError`` and :data:`NotImplemented` are not interchangeable, "
"even though they have similar names and purposes.  See :data:`!"
"NotImplemented` for details on when to use it."
msgstr ""
"``NotImplementedError`` e :data:`NotImplemented` não são intercambiáveis, "
"mesmo que tenham nomes e propósitos similares.  Veja :data:`!NotImplemented` "
"para detalhes e casos de uso."

#: ../../library/exceptions.rst:347
msgid ""
"This exception is raised when a system function returns a system-related "
"error, including I/O failures such as \"file not found\" or \"disk "
"full\" (not for illegal argument types or other incidental errors)."
msgstr ""
"Esta exceção é levantada quando uma função do sistema retorna um erro "
"relacionado ao sistema, incluindo falhas do tipo E/S como \"file not found\" "
"ou \"disk full\" (não para tipos de argumentos não permitidos ou outro erro "
"acessório)."

#: ../../library/exceptions.rst:351
msgid ""
"The second form of the constructor sets the corresponding attributes, "
"described below.  The attributes default to :const:`None` if not specified.  "
"For backwards compatibility, if three arguments are passed, the :attr:"
"`~BaseException.args` attribute contains only a 2-tuple of the first two "
"constructor arguments."
msgstr ""
"A segunda forma do construtor definir os atributos correspondentes, "
"descritos abaixo.  Os atributos usarão o valor padrão :const:`None` se não "
"forem especificados.  Por compatibilidade com versões anteriores, se três "
"argumentos são passados, o atributo :attr:`~BaseException.args` contêm "
"somente uma tupla de 2 elementos, os dois primeiros argumentos do construtor."

#: ../../library/exceptions.rst:357
msgid ""
"The constructor often actually returns a subclass of :exc:`OSError`, as "
"described in `OS exceptions`_ below.  The particular subclass depends on the "
"final :attr:`.errno` value.  This behaviour only occurs when constructing :"
"exc:`OSError` directly or via an alias, and is not inherited when "
"subclassing."
msgstr ""
"O construtor geralmente retorna uma subclasse de :exc:`OSError`, como "
"descrito abaixo em `OS exceptions`_ .  A subclasse particular depende do "
"valor final de :attr:`.errno`.  Este comportamento ocorre apenas durante a "
"construção direta ou por meio de um apelido de :exc:`OSError`, e não é "
"herdado na criação de subclasses."

#: ../../library/exceptions.rst:365
msgid "A numeric error code from the C variable :c:data:`errno`."
msgstr "Um código de erro numérico da variável C :c:data:`errno`."

#: ../../library/exceptions.rst:369
msgid ""
"Under Windows, this gives you the native Windows error code.  The :attr:`."
"errno` attribute is then an approximate translation, in POSIX terms, of that "
"native error code."
msgstr ""
"No Windows, isso fornece o código de erro nativo do Windows. O atributo :"
"attr:`.errno` é então uma tradução aproximada, em termos POSIX, desse código "
"de erro nativo."

#: ../../library/exceptions.rst:373
msgid ""
"Under Windows, if the *winerror* constructor argument is an integer, the :"
"attr:`.errno` attribute is determined from the Windows error code, and the "
"*errno* argument is ignored.  On other platforms, the *winerror* argument is "
"ignored, and the :attr:`winerror` attribute does not exist."
msgstr ""
"No Windows, se o argumento de construtor *winerror* for um inteiro, o "
"atributo :attr:`.errno` é determinado a partir do código de erro do Windows "
"e o argumento *errno* é ignorado. Em outras plataformas, o argumento "
"*winerror* é ignorado e o atributo :attr:`winerror` não existe."

#: ../../library/exceptions.rst:381
msgid ""
"The corresponding error message, as provided by the operating system.  It is "
"formatted by the C functions :c:func:`perror` under POSIX, and :c:func:"
"`FormatMessage` under Windows."
msgstr ""
"A mensagem de erro correspondente, conforme fornecida pelo sistema "
"operacional. É formatada pelas funções C :c:func:`perror` no POSIX e :c:func:"
"`FormatMessage` no Windows."

#: ../../library/exceptions.rst:389
msgid ""
"For exceptions that involve a file system path (such as :func:`open` or :"
"func:`os.unlink`), :attr:`filename` is the file name passed to the function. "
"For functions that involve two file system paths (such as :func:`os."
"rename`), :attr:`filename2` corresponds to the second file name passed to "
"the function."
msgstr ""
"Para exceções que envolvem um caminho do sistema de arquivos (como :func:"
"`open` ou :func:`os.unlink`), :attr:`filename` é o nome do arquivo passado "
"para a função. Para funções que envolvem dois caminhos de sistema de "
"arquivos (como :func:`os.rename`), :attr:`filename2` corresponde ao segundo "
"nome de arquivo passado para a função."

#: ../../library/exceptions.rst:396
msgid ""
":exc:`EnvironmentError`, :exc:`IOError`, :exc:`WindowsError`, :exc:`socket."
"error`, :exc:`select.error` and :exc:`mmap.error` have been merged into :exc:"
"`OSError`, and the constructor may return a subclass."
msgstr ""
":exc:`EnvironmentError`, :exc:`IOError`, :exc:`WindowsError`, :exc:`socket."
"error`, :exc:`select.error` e :exc:`mmap.error` foram fundidos em :exc:"
"`OSError`, e o construtor pode retornar uma subclasse."

#: ../../library/exceptions.rst:402
msgid ""
"The :attr:`filename` attribute is now the original file name passed to the "
"function, instead of the name encoded to or decoded from the :term:"
"`filesystem encoding and error handler`. Also, the *filename2* constructor "
"argument and attribute was added."
msgstr ""
"O atributo :attr:`filename` agora é o nome do arquivo original passado para "
"a função, ao invés do nome codificado ou decodificado da :term:`tratador de "
"erros e codificação do sistema de arquivos`. Além disso, o argumento e o "
"atributo de construtor *filename2* foi adicionado."

#: ../../library/exceptions.rst:411
msgid ""
"Raised when the result of an arithmetic operation is too large to be "
"represented.  This cannot occur for integers (which would rather raise :exc:"
"`MemoryError` than give up).  However, for historical reasons, OverflowError "
"is sometimes raised for integers that are outside a required range.   "
"Because of the lack of standardization of floating-point exception handling "
"in C, most floating-point operations are not checked."
msgstr ""
"Levantada quando o resultado de uma operação aritmética é muito grande para "
"ser representada. Isso não pode ocorrer para inteiros (que prefere levantar :"
"exc:`MemoryError` a desistir). No entanto, por motivos históricos, "
"OverflowError às vezes é levantada para inteiros que estão fora de um "
"intervalo obrigatório. Devido à falta de padronização do tratamento de "
"exceção de ponto flutuante em C, a maioria das operações de ponto flutuante "
"não são verificadas."

#: ../../library/exceptions.rst:421
msgid ""
"This exception is derived from :exc:`RuntimeError`.  It is raised when the "
"interpreter detects that the maximum recursion depth (see :func:`sys."
"getrecursionlimit`) is exceeded."
msgstr ""
"Esta exceção é derivada de :exc:`RuntimeError`. É levantada quando o "
"interpretador detecta que a profundidade máxima de recursão (veja :func:`sys."
"getrecursionlimit`) foi excedida."

#: ../../library/exceptions.rst:425
msgid "Previously, a plain :exc:`RuntimeError` was raised."
msgstr "Anteriormente, uma :exc:`RuntimeError` simples era levantada."

#: ../../library/exceptions.rst:431
msgid ""
"This exception is raised when a weak reference proxy, created by the :func:"
"`weakref.proxy` function, is used to access an attribute of the referent "
"after it has been garbage collected. For more information on weak "
"references, see the :mod:`weakref` module."
msgstr ""
"Esta exceção é levantada quando um intermediário de referência fraca, criado "
"pela função :func:`weakref.proxy`, é usado para acessar um atributo do "
"referente após ter sido coletado como lixo. Para mais informações sobre "
"referências fracas, veja o módulo :mod:`weakref`."

#: ../../library/exceptions.rst:439
msgid ""
"Raised when an error is detected that doesn't fall in any of the other "
"categories.  The associated value is a string indicating what precisely went "
"wrong."
msgstr ""
"Levantada quando um erro é detectado e não se encaixa em nenhuma das outras "
"categorias. O valor associado é uma string indicando o que precisamente deu "
"errado."

#: ../../library/exceptions.rst:446
msgid ""
"Raised by built-in function :func:`next` and an :term:`iterator`\\'s :meth:"
"`~iterator.__next__` method to signal that there are no further items "
"produced by the iterator."
msgstr ""
"Levantada pela função embutida :func:`next` e o método :meth:`~iterator."
"__next__` de um :term:`iterador` para sinalizar que não há mais itens "
"produzidos pelo iterador."

#: ../../library/exceptions.rst:452
msgid ""
"The exception object has a single attribute :attr:`!value`, which is given "
"as an argument when constructing the exception, and defaults to :const:"
"`None`."
msgstr ""
"O objeto exceção tem um único atributo :attr:`!value`, que é fornecido como "
"um argumento ao construir a exceção, e o padrão é :const:`None`."

#: ../../library/exceptions.rst:456
msgid ""
"When a :term:`generator` or :term:`coroutine` function returns, a new :exc:"
"`StopIteration` instance is raised, and the value returned by the function "
"is used as the :attr:`value` parameter to the constructor of the exception."
msgstr ""
"Quando uma função :term:`geradora <gerador>` ou :term:`corrotina` retorna, "
"uma nova instância :exc:`StopIteration` é levantada, e o valor retornado "
"pela função é usado como o parâmetro :attr:`value` para o construtor da "
"exceção."

#: ../../library/exceptions.rst:461
msgid ""
"If a generator code directly or indirectly raises :exc:`StopIteration`, it "
"is converted into a :exc:`RuntimeError` (retaining the :exc:`StopIteration` "
"as the new exception's cause)."
msgstr ""
"Se um código gerador direta ou indiretamente levantar :exc:`StopIteration`, "
"ele é convertido em uma :exc:`RuntimeError` (mantendo o :exc:`StopIteration` "
"como a nova causa da exceção)."

#: ../../library/exceptions.rst:465
msgid ""
"Added ``value`` attribute and the ability for generator functions to use it "
"to return a value."
msgstr ""
"Adicionado o atributo ``value`` e a capacidade das funções geradoras de usá-"
"lo para retornar um valor."

#: ../../library/exceptions.rst:469
msgid ""
"Introduced the RuntimeError transformation via ``from __future__ import "
"generator_stop``, see :pep:`479`."
msgstr ""
"Introduzida a transformação RuntimeError via ``from __future__ import "
"generator_stop``, consulte :pep:`479`."

#: ../../library/exceptions.rst:473
msgid ""
"Enable :pep:`479` for all code by default: a :exc:`StopIteration` error "
"raised in a generator is transformed into a :exc:`RuntimeError`."
msgstr ""
"Habilita :pep:`479` para todo o código por padrão: um erro :exc:"
"`StopIteration` levantado em um gerador é transformado em uma :exc:"
"`RuntimeError`."

#: ../../library/exceptions.rst:479
msgid ""
"Must be raised by :meth:`~object.__anext__` method of an :term:`asynchronous "
"iterator` object to stop the iteration."
msgstr ""
"Deve ser levantada pelo método :meth:`~object.__anext__` de um objeto :term:"
"`iterador assíncrono` para parar a iteração."

#: ../../library/exceptions.rst:486
msgid ""
"Raised when the parser encounters a syntax error.  This may occur in an :"
"keyword:`import` statement, in a call to the built-in functions :func:"
"`compile`, :func:`exec`, or :func:`eval`, or when reading the initial script "
"or standard input (also interactively)."
msgstr ""
"Levantada quando o analisador encontra um erro de sintaxe. Isso pode ocorrer "
"em uma instrução :keyword:`import`, em uma chamada às funções embutidas :"
"func:`compile`, :func:`exec` ou :func:`eval`, ou ao ler o script inicial ou "
"entrada padrão (também interativamente)."

#: ../../library/exceptions.rst:492
msgid ""
"The :func:`str` of the exception instance returns only the error message. "
"Details is a tuple whose members are also available as separate attributes."
msgstr ""
"A função :func:`str` da instância de exceção retorna apenas a mensagem de "
"erro. Detalhes é uma tupla cujos membros também estão disponíveis como "
"atributos separados."

#: ../../library/exceptions.rst:497
msgid "The name of the file the syntax error occurred in."
msgstr "O nome do arquivo em que ocorreu o erro de sintaxe."

#: ../../library/exceptions.rst:501
msgid ""
"Which line number in the file the error occurred in. This is 1-indexed: the "
"first line in the file has a ``lineno`` of 1."
msgstr ""
"Em qual número de linha no arquivo o erro ocorreu. Este é indexado em 1: a "
"primeira linha no arquivo tem um ``lineno`` de 1."

#: ../../library/exceptions.rst:506
msgid ""
"The column in the line where the error occurred. This is 1-indexed: the "
"first character in the line has an ``offset`` of 1."
msgstr ""
"A coluna da linha em que ocorreu o erro. Este é indexado em 1: o primeiro "
"caractere na linha tem um ``offset`` de 1."

#: ../../library/exceptions.rst:511
msgid "The source code text involved in the error."
msgstr "O texto do código-fonte envolvido no erro."

#: ../../library/exceptions.rst:515
msgid ""
"Which line number in the file the error occurred ends in. This is 1-indexed: "
"the first line in the file has a ``lineno`` of 1."
msgstr ""
"Em qual número de linha no arquivo o erro ocorrido termina. Este é indexado "
"em 1: a primeira linha no arquivo tem um ``lineno`` de 1."

#: ../../library/exceptions.rst:520
msgid ""
"The column in the end line where the error occurred finishes. This is 1-"
"indexed: the first character in the line has an ``offset`` of 1."
msgstr ""
"A coluna da linha final em que erro ocorrido finaliza Este é indexado em 1: "
"o primeiro caractere na linha tem um ``offset`` de 1."

#: ../../library/exceptions.rst:523
msgid ""
"For errors in f-string fields, the message is prefixed by \"f-string: \" and "
"the offsets are offsets in a text constructed from the replacement "
"expression.  For example, compiling f'Bad {a b} field' results in this args "
"attribute: ('f-string: ...', ('', 1, 2, '(a b)\\n', 1, 5))."
msgstr ""
"Para erros em campos de f-string, a mensagem é prefixada por \"f-string: \" "
"e os \"offsets\" são deslocamentos em um texto construído a partir da "
"expressão de substituição. Por exemplo, compilar o campo f'Bad {a b}' "
"resulta neste atributo de argumentos: ('f-string: ...', ('', 1, 2, '(a "
"b)\\n', 1, 5))."

#: ../../library/exceptions.rst:528
msgid "Added the :attr:`end_lineno` and :attr:`end_offset` attributes."
msgstr "Adicionado os atributos :attr:`end_lineno` e :attr:`end_offset`."

#: ../../library/exceptions.rst:533
msgid ""
"Base class for syntax errors related to incorrect indentation.  This is a "
"subclass of :exc:`SyntaxError`."
msgstr ""
"Classe base para erros de sintaxe relacionados a indentação incorreta. Esta "
"é uma subclasse de :exc:`SyntaxError`."

#: ../../library/exceptions.rst:539
msgid ""
"Raised when indentation contains an inconsistent use of tabs and spaces. "
"This is a subclass of :exc:`IndentationError`."
msgstr ""
"Levantada quando o indentação contém um uso inconsistente de tabulações e "
"espaços. Esta é uma subclasse de :exc:`IndentationError`."

#: ../../library/exceptions.rst:545
msgid ""
"Raised when the interpreter finds an internal error, but the situation does "
"not look so serious to cause it to abandon all hope. The associated value is "
"a string indicating what went wrong (in low-level terms)."
msgstr ""
"Levantada quando o interpretador encontra um erro interno, mas a situação "
"não parece tão grave para fazer com que perca todas as esperanças. O valor "
"associado é uma string que indica o que deu errado (em termos de baixo "
"nível)."

#: ../../library/exceptions.rst:549
msgid ""
"You should report this to the author or maintainer of your Python "
"interpreter. Be sure to report the version of the Python interpreter (``sys."
"version``; it is also printed at the start of an interactive Python "
"session), the exact error message (the exception's associated value) and if "
"possible the source of the program that triggered the error."
msgstr ""
"Você deve relatar isso ao autor ou mantenedor do seu interpretador Python. "
"Certifique-se de relatar a versão do interpretador Python (``sys.version``; "
"também é impresso no início de uma sessão Python interativa), a mensagem de "
"erro exata (o valor associado da exceção) e se possível a fonte do programa "
"que acionou o erro."

#: ../../library/exceptions.rst:558
msgid ""
"This exception is raised by the :func:`sys.exit` function.  It inherits "
"from :exc:`BaseException` instead of :exc:`Exception` so that it is not "
"accidentally caught by code that catches :exc:`Exception`.  This allows the "
"exception to properly propagate up and cause the interpreter to exit.  When "
"it is not handled, the Python interpreter exits; no stack traceback is "
"printed.  The constructor accepts the same optional argument passed to :func:"
"`sys.exit`. If the value is an integer, it specifies the system exit status "
"(passed to C's :c:func:`exit` function); if it is ``None``, the exit status "
"is zero; if it has another type (such as a string), the object's value is "
"printed and the exit status is one."
msgstr ""
"Esta exceção é levantada pela função :func:`sys.exit`. Ele herda de :exc:"
"`BaseException` em vez de  :exc:`Exception` para que não seja acidentalmente "
"capturado pelo código que captura :exc:`Exception`. Isso permite que a "
"exceção se propague corretamente e faça com que o interpretador saia. Quando "
"não é tratado, o interpretador Python sai; nenhum traceback (situação da "
"pilha de execução) é impresso. O construtor aceita o mesmo argumento "
"opcional passado para :func:`sys.exit`. Se o valor for um inteiro, ele "
"especifica o status de saída do sistema (passado para a função C :c:func:"
"`exit`); se for ``None``, o status de saída é zero; se tiver outro tipo "
"(como uma string), o valor do objeto é exibido e o status de saída é um."

#: ../../library/exceptions.rst:569
msgid ""
"A call to :func:`sys.exit` is translated into an exception so that clean-up "
"handlers (:keyword:`finally` clauses of :keyword:`try` statements) can be "
"executed, and so that a debugger can execute a script without running the "
"risk of losing control.  The :func:`os._exit` function can be used if it is "
"absolutely positively necessary to exit immediately (for example, in the "
"child process after a call to :func:`os.fork`)."
msgstr ""
"Uma chamada para :func:`sys.exit` é traduzida em uma exceção para que os "
"tratadores de limpeza (cláusulas :keyword:`finally` das instruções :keyword:"
"`try`) possam ser executados, e para que um depurador possa executar um "
"script sem correr o risco de perder o controle. A função :func:`os._exit` "
"pode ser usada se for absolutamente necessário sair imediatamente (por "
"exemplo, no processo filho após uma chamada para :func:`os.fork`)."

#: ../../library/exceptions.rst:578
msgid ""
"The exit status or error message that is passed to the constructor. "
"(Defaults to ``None``.)"
msgstr ""
"O status de saída ou mensagem de erro transmitida ao construtor. (O padrão é "
"``None``.)"

#: ../../library/exceptions.rst:584
msgid ""
"Raised when an operation or function is applied to an object of "
"inappropriate type.  The associated value is a string giving details about "
"the type mismatch."
msgstr ""
"Levantada quando uma operação ou função é aplicada a um objeto de tipo "
"inadequado. O valor associado é uma string que fornece detalhes sobre a "
"incompatibilidade de tipo."

#: ../../library/exceptions.rst:587
msgid ""
"This exception may be raised by user code to indicate that an attempted "
"operation on an object is not supported, and is not meant to be. If an "
"object is meant to support a given operation but has not yet provided an "
"implementation, :exc:`NotImplementedError` is the proper exception to raise."
msgstr ""
"Essa exceção pode ser levantada pelo código do usuário para indicar que uma "
"tentativa de operação em um objeto não é suportada e não deveria ser. Se um "
"objeto deve ter suporte a uma dada operação, mas ainda não forneceu uma "
"implementação, :exc:`NotImplementedError` é a exceção apropriada a ser "
"levantada."

#: ../../library/exceptions.rst:592
msgid ""
"Passing arguments of the wrong type (e.g. passing a :class:`list` when an :"
"class:`int` is expected) should result in a :exc:`TypeError`, but passing "
"arguments with the wrong value (e.g. a number outside expected boundaries) "
"should result in a :exc:`ValueError`."
msgstr ""
"Passar argumentos do tipo errado (por exemplo, passar uma :class:`list` "
"quando um :class:`int` é esperado) deve resultar em uma :exc:`TypeError`, "
"mas passar argumentos com o valor errado (por exemplo, um número fora "
"limites esperados) deve resultar em uma :exc:`ValueError`."

#: ../../library/exceptions.rst:599
msgid ""
"Raised when a reference is made to a local variable in a function or method, "
"but no value has been bound to that variable.  This is a subclass of :exc:"
"`NameError`."
msgstr ""
"Levantada quando uma referência é feita a uma variável local em uma função "
"ou método, mas nenhum valor foi vinculado a essa variável. Esta é uma "
"subclasse de :exc:`NameError`."

#: ../../library/exceptions.rst:606
msgid ""
"Raised when a Unicode-related encoding or decoding error occurs.  It is a "
"subclass of :exc:`ValueError`."
msgstr ""
"Levantada quando ocorre um erro de codificação ou decodificação relacionado "
"ao Unicode. É uma subclasse de :exc:`ValueError`."

#: ../../library/exceptions.rst:609
msgid ""
":exc:`UnicodeError` has attributes that describe the encoding or decoding "
"error.  For example, ``err.object[err.start:err.end]`` gives the particular "
"invalid input that the codec failed on."
msgstr ""
":exc:`UnicodeError` possui atributos que descrevem o erro de codificação ou "
"decodificação. Por exemplo, ``err.object[err.start:err.end]`` fornece a "
"entrada inválida específica na qual o codec falhou."

#: ../../library/exceptions.rst:615
msgid "The name of the encoding that raised the error."
msgstr "O nome da codificação que levantou o erro."

#: ../../library/exceptions.rst:619
msgid "A string describing the specific codec error."
msgstr "Uma string que descreve o erro de codec específico."

#: ../../library/exceptions.rst:623
msgid "The object the codec was attempting to encode or decode."
msgstr "O objeto que o codec estava tentando codificar ou decodificar."

#: ../../library/exceptions.rst:627
msgid "The first index of invalid data in :attr:`object`."
msgstr "O primeiro índice de dados inválidos em :attr:`object`."

#: ../../library/exceptions.rst:631
msgid "The index after the last invalid data in :attr:`object`."
msgstr "O índice após os últimos dados inválidos em :attr:`object`."

#: ../../library/exceptions.rst:636
msgid ""
"Raised when a Unicode-related error occurs during encoding.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Levantada quando ocorre um erro relacionado ao Unicode durante a "
"codificação. É uma subclasse de :exc:`UnicodeError`."

#: ../../library/exceptions.rst:642
msgid ""
"Raised when a Unicode-related error occurs during decoding.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Levantada quando ocorre um erro relacionado ao Unicode durante a "
"decodificação. É uma subclasse de :exc:`UnicodeError`."

#: ../../library/exceptions.rst:648
msgid ""
"Raised when a Unicode-related error occurs during translating.  It is a "
"subclass of :exc:`UnicodeError`."
msgstr ""
"Levantada quando ocorre um erro relacionado ao Unicode durante a tradução. É "
"uma subclasse de :exc:`UnicodeError`."

#: ../../library/exceptions.rst:654
msgid ""
"Raised when an operation or function receives an argument that has the right "
"type but an inappropriate value, and the situation is not described by a "
"more precise exception such as :exc:`IndexError`."
msgstr ""
"Levantada quando uma operação ou função recebe um argumento que tem o tipo "
"certo, mas um valor inadequado, e a situação não é descrita por uma exceção "
"mais precisa, como :exc:`IndexError`."

#: ../../library/exceptions.rst:661
msgid ""
"Raised when the second argument of a division or modulo operation is zero.  "
"The associated value is a string indicating the type of the operands and the "
"operation."
msgstr ""
"Levantada quando o segundo argumento de uma divisão ou operação de módulo é "
"zero. O valor associado é uma string que indica o tipo dos operandos e a "
"operação."

#: ../../library/exceptions.rst:666
msgid ""
"The following exceptions are kept for compatibility with previous versions; "
"starting from Python 3.3, they are aliases of :exc:`OSError`."
msgstr ""
"As seguintes exceções são mantidas para compatibilidade com versões "
"anteriores; a partir do Python 3.3, eles são apelidos de :exc:`OSError`."

#: ../../library/exceptions.rst:675
msgid "Only available on Windows."
msgstr "Disponível apenas no Windows."

#: ../../library/exceptions.rst:679
msgid "OS exceptions"
msgstr "Exceções de sistema operacional"

#: ../../library/exceptions.rst:681
msgid ""
"The following exceptions are subclasses of :exc:`OSError`, they get raised "
"depending on the system error code."
msgstr ""
"As seguintes exceções são subclasses de :exc:`OSError`, elas são levantadas "
"dependendo do código de erro do sistema."

#: ../../library/exceptions.rst:686
msgid ""
"Raised when an operation would block on an object (e.g. socket) set for non-"
"blocking operation. Corresponds to :c:data:`errno` :py:const:`~errno."
"EAGAIN`, :py:const:`~errno.EALREADY`, :py:const:`~errno.EWOULDBLOCK` and :py:"
"const:`~errno.EINPROGRESS`."
msgstr ""
"Levantada quando uma operação bloquearia em um objeto (por exemplo, soquete) "
"definido para operação sem bloqueio. Corresponde a :c:data:`errno` :py:const:"
"`~errno.EAGAIN`, :py:const:`~errno.EALREADY`, :py:const:`~errno.EWOULDBLOCK` "
"e :py:const:`~errno.EINPROGRESS`."

#: ../../library/exceptions.rst:691
msgid ""
"In addition to those of :exc:`OSError`, :exc:`BlockingIOError` can have one "
"more attribute:"
msgstr ""
"Além daquelas de :exc:`OSError`, :exc:`BlockingIOError` pode ter mais um "
"atributo:"

#: ../../library/exceptions.rst:696
msgid ""
"An integer containing the number of characters written to the stream before "
"it blocked.  This attribute is available when using the buffered I/O classes "
"from the :mod:`io` module."
msgstr ""
"Um inteiro contendo o número de caracteres gravados no fluxo antes de ser "
"bloqueado. Este atributo está disponível ao usar as classes de E/S em buffer "
"do módulo :mod:`io`."

#: ../../library/exceptions.rst:702
msgid ""
"Raised when an operation on a child process failed. Corresponds to :c:data:"
"`errno` :py:const:`~errno.ECHILD`."
msgstr ""
"Levantada quando uma operação em um processo filho falha. Corresponde a :c:"
"data:`errno` :py:const:`~errno.ECHILD`."

#: ../../library/exceptions.rst:707
msgid "A base class for connection-related issues."
msgstr "Uma classe base para problemas relacionados à conexão."

#: ../../library/exceptions.rst:709
msgid ""
"Subclasses are :exc:`BrokenPipeError`, :exc:`ConnectionAbortedError`, :exc:"
"`ConnectionRefusedError` and :exc:`ConnectionResetError`."
msgstr ""
"Suas subclasses são :exc:`BrokenPipeError`, :exc:`ConnectionAbortedError`, :"
"exc:`ConnectionRefusedError` e :exc:`ConnectionResetError`."

#: ../../library/exceptions.rst:714
msgid ""
"A subclass of :exc:`ConnectionError`, raised when trying to write on a pipe "
"while the other end has been closed, or trying to write on a socket which "
"has been shutdown for writing. Corresponds to :c:data:`errno` :py:const:"
"`~errno.EPIPE` and :py:const:`~errno.ESHUTDOWN`."
msgstr ""
"Uma subclasse de :exc:`ConnectionError`,  levantada ao tentar escrever em um "
"encadeamento, enquanto a outra extremidade foi fechada, ou ao tentar "
"escrever em um soquete que foi desligado para escrita. Corresponde a  :c:"
"data:`errno` :py:const:`~errno.EPIPE` e :py:const:`~errno.ESHUTDOWN`."

#: ../../library/exceptions.rst:721
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection attempt is "
"aborted by the peer. Corresponds to :c:data:`errno` :py:const:`~errno."
"ECONNABORTED`."
msgstr ""
"Uma subclasse de :exc:`ConnectionError`, levantada quando uma tentativa de "
"conexão é cancelada pelo par. Corresponde a :c:data:`errno` :py:const:"
"`~errno.ECONNABORTED`."

#: ../../library/exceptions.rst:727
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection attempt is "
"refused by the peer. Corresponds to :c:data:`errno` :py:const:`~errno."
"ECONNREFUSED`."
msgstr ""
"Uma subclasse de :exc:`ConnectionError`, levantada quando uma tentativa de "
"conexão é recusada pelo par. Corresponde a :c:data:`errno` :py:const:`~errno."
"ECONNREFUSED`."

#: ../../library/exceptions.rst:733
msgid ""
"A subclass of :exc:`ConnectionError`, raised when a connection is reset by "
"the peer. Corresponds to :c:data:`errno` :py:const:`~errno.ECONNRESET`."
msgstr ""
"Uma subclasse de :exc:`ConnectionError`, levantada quando uma conexão é "
"redefinida pelo par. Corresponde a :c:data:`errno` :py:const:`~errno."
"ECONNRESET`."

#: ../../library/exceptions.rst:739
msgid ""
"Raised when trying to create a file or directory which already exists. "
"Corresponds to :c:data:`errno` :py:const:`~errno.EEXIST`."
msgstr ""
"Levantada ao tentar criar um arquivo ou diretório que já existe. Corresponde "
"a :c:data:`errno` :py:const:`~errno.EEXIST`."

#: ../../library/exceptions.rst:744
msgid ""
"Raised when a file or directory is requested but doesn't exist. Corresponds "
"to :c:data:`errno` :py:const:`~errno.ENOENT`."
msgstr ""
"Levantada quando um arquivo ou diretório é solicitado, mas não existe. "
"Corresponde a :c:data:`errno` :py:const:`~errno.ENOENT`."

#: ../../library/exceptions.rst:749
msgid ""
"Raised when a system call is interrupted by an incoming signal. Corresponds "
"to :c:data:`errno` :py:const:`~errno.EINTR`."
msgstr ""
"Levantada quando uma chamada do sistema é interrompida por um sinal de "
"entrada. Corresponde a :c:data:`errno` :py:const:`~errno.EINTR`."

#: ../../library/exceptions.rst:752
msgid ""
"Python now retries system calls when a syscall is interrupted by a signal, "
"except if the signal handler raises an exception (see :pep:`475` for the "
"rationale), instead of raising :exc:`InterruptedError`."
msgstr ""
"Python agora tenta novamente chamadas de sistema quando uma *syscall* é "
"interrompida por um sinal, exceto se o tratador de sinal levanta uma exceção "
"(veja :pep:`475` para a justificativa), em vez de levantar :exc:"
"`InterruptedError`."

#: ../../library/exceptions.rst:759
msgid ""
"Raised when a file operation (such as :func:`os.remove`) is requested on a "
"directory. Corresponds to :c:data:`errno` :py:const:`~errno.EISDIR`."
msgstr ""
"Levantada quando uma operação de arquivo (como :func:`os.remove`) é "
"solicitada em um diretório. Corresponde a :c:data:`errno` :py:const:`~errno."
"EISDIR`."

#: ../../library/exceptions.rst:765
msgid ""
"Raised when a directory operation (such as :func:`os.listdir`) is requested "
"on something which is not a directory.  On most POSIX platforms, it may also "
"be raised if an operation attempts to open or traverse a non-directory file "
"as if it were a directory. Corresponds to :c:data:`errno` :py:const:`~errno."
"ENOTDIR`."
msgstr ""
"Levantada quando uma operação de diretório (como :func:`os.listdir`) é "
"solicitada em algo que não é um diretório. Na maioria das plataformas POSIX, "
"ela também pode ser levantada se uma operação tentar abrir ou percorrer um "
"arquivo não pertencente ao diretório como se fosse um diretório. Corresponde "
"a :c:data:`errno` :py:const:`~errno.ENOTDIR`."

#: ../../library/exceptions.rst:773
msgid ""
"Raised when trying to run an operation without the adequate access rights - "
"for example filesystem permissions. Corresponds to :c:data:`errno` :py:const:"
"`~errno.EACCES`, :py:const:`~errno.EPERM`, and :py:const:`~errno."
"ENOTCAPABLE`."
msgstr ""
"Levantada ao tentar executar uma operação sem os direitos de acesso "
"adequados - por exemplo, permissões do sistema de arquivos. Corresponde a :c:"
"data:`errno` :py:const:`~errno.EACCES`, :py:const:`~errno.EPERM`, e :py:"
"const:`~errno.ENOTCAPABLE`."

#: ../../library/exceptions.rst:778
msgid ""
"WASI's :py:const:`~errno.ENOTCAPABLE` is now mapped to :exc:"
"`PermissionError`."
msgstr ""
":py:const:`~errno.ENOTCAPABLE` do WASI agora é mapeado para :exc:"
"`PermissionError`."

#: ../../library/exceptions.rst:784
msgid ""
"Raised when a given process doesn't exist. Corresponds to :c:data:`errno` :"
"py:const:`~errno.ESRCH`."
msgstr ""
"Levantada quando um determinado processo não existe. Corresponde a :c:data:"
"`errno` :py:const:`~errno.ESRCH`."

#: ../../library/exceptions.rst:789
msgid ""
"Raised when a system function timed out at the system level. Corresponds to :"
"c:data:`errno` :py:const:`~errno.ETIMEDOUT`."
msgstr ""
"Levantada quando uma função do sistema expirou no nível do sistema. "
"Corresponde a :c:data:`errno` :py:const:`~errno.ETIMEDOUT`."

#: ../../library/exceptions.rst:792
msgid "All the above :exc:`OSError` subclasses were added."
msgstr "Todas as subclasses de :exc:`OSError` acima foram adicionadas."

#: ../../library/exceptions.rst:798
msgid ":pep:`3151` - Reworking the OS and IO exception hierarchy"
msgstr ":pep:`3151` - Reworking the OS and IO exception hierarchy"

#: ../../library/exceptions.rst:804
msgid "Warnings"
msgstr "Avisos"

#: ../../library/exceptions.rst:806
msgid ""
"The following exceptions are used as warning categories; see the :ref:"
"`warning-categories` documentation for more details."
msgstr ""
"As seguintes exceções são usadas como categorias de aviso; veja a "
"documentação de :ref:`warning-categories` para mais detalhes."

#: ../../library/exceptions.rst:811
msgid "Base class for warning categories."
msgstr "Classe base para categorias de aviso."

#: ../../library/exceptions.rst:816
msgid "Base class for warnings generated by user code."
msgstr "Classe base para avisos gerados pelo código do usuário."

#: ../../library/exceptions.rst:821
msgid ""
"Base class for warnings about deprecated features when those warnings are "
"intended for other Python developers."
msgstr ""
"Classe base para avisos sobre recursos descontinuados quando esses avisos se "
"destinam a outros desenvolvedores Python."

#: ../../library/exceptions.rst:824
msgid ""
"Ignored by the default warning filters, except in the ``__main__`` module (:"
"pep:`565`). Enabling the :ref:`Python Development Mode <devmode>` shows this "
"warning."
msgstr ""
"Ignorado pelos filtros de aviso padrão, exceto no módulo ``__main__`` (:pep:"
"`565`). Habilitar o :ref:`Modo de Desenvolvimento do Python <devmode>` "
"mostra este aviso."

#: ../../library/exceptions.rst:828 ../../library/exceptions.rst:844
msgid "The deprecation policy is described in :pep:`387`."
msgstr "A política de descontinuação está descrita na :pep:`387`."

#: ../../library/exceptions.rst:833
msgid ""
"Base class for warnings about features which are obsolete and expected to be "
"deprecated in the future, but are not deprecated at the moment."
msgstr ""
"Classe base para avisos sobre recursos que foram descontinuados e devem ser "
"descontinuados no futuro, mas não foram descontinuados ainda."

#: ../../library/exceptions.rst:837
msgid ""
"This class is rarely used as emitting a warning about a possible upcoming "
"deprecation is unusual, and :exc:`DeprecationWarning` is preferred for "
"already active deprecations."
msgstr ""
"Esta classe raramente é usada para emitir um aviso sobre uma possível "
"descontinuação futura, é incomum, e :exc:`DeprecationWarning` é preferível "
"para descontinuações já ativas."

#: ../../library/exceptions.rst:841 ../../library/exceptions.rst:867
#: ../../library/exceptions.rst:894
msgid ""
"Ignored by the default warning filters. Enabling the :ref:`Python "
"Development Mode <devmode>` shows this warning."
msgstr ""
"Ignorado pelos filtros de aviso padrão. Habilitar o :ref:`Modo de "
"Desenvolvimento do Python <devmode>` mostra este aviso."

#: ../../library/exceptions.rst:849
msgid "Base class for warnings about dubious syntax."
msgstr "Classe base para avisos sobre sintaxe duvidosa."

#: ../../library/exceptions.rst:854
msgid "Base class for warnings about dubious runtime behavior."
msgstr ""
"Classe base para avisos sobre comportamento duvidoso de tempo de execução."

#: ../../library/exceptions.rst:859
msgid ""
"Base class for warnings about deprecated features when those warnings are "
"intended for end users of applications that are written in Python."
msgstr ""
"Classe base para avisos sobre recursos descontinuados quando esses avisos se "
"destinam a usuários finais de aplicações escritas em Python."

#: ../../library/exceptions.rst:865
msgid "Base class for warnings about probable mistakes in module imports."
msgstr ""
"Classe base para avisos sobre prováveis erros na importação de módulos."

#: ../../library/exceptions.rst:873
msgid "Base class for warnings related to Unicode."
msgstr "Classe base para avisos relacionados a Unicode."

#: ../../library/exceptions.rst:878
msgid "Base class for warnings related to encodings."
msgstr "Classe base para avisos relacionados a codificações."

#: ../../library/exceptions.rst:880
msgid "See :ref:`io-encoding-warning` for details."
msgstr "Veja :ref:`io-encoding-warning` para detalhes."

#: ../../library/exceptions.rst:887
msgid ""
"Base class for warnings related to :class:`bytes` and :class:`bytearray`."
msgstr ""
"Classe base para avisos relacionados a :class:`bytes` e :class:`bytearray`."

#: ../../library/exceptions.rst:892
msgid "Base class for warnings related to resource usage."
msgstr "Classe base para avisos relacionados a uso de recursos."

#: ../../library/exceptions.rst:903
msgid "Exception groups"
msgstr "Grupos de exceções"

#: ../../library/exceptions.rst:905
msgid ""
"The following are used when it is necessary to raise multiple unrelated "
"exceptions. They are part of the exception hierarchy so they can be handled "
"with :keyword:`except` like all other exceptions. In addition, they are "
"recognised by :keyword:`except*<except_star>`, which matches their subgroups "
"based on the types of the contained exceptions."
msgstr ""
"Os itens a seguir são usados quando é necessário levantar várias exceções "
"não relacionadas. Eles fazem parte da hierarquia de exceção, portanto, podem "
"ser tratados com :keyword:`except` como todas as outras exceções. Além "
"disso, eles são reconhecidos por :keyword:`except*<except_star>`, que "
"corresponde a seus subgrupos com base nos tipos de exceções contidas."

#: ../../library/exceptions.rst:914
msgid ""
"Both of these exception types wrap the exceptions in the sequence ``excs``. "
"The ``msg`` parameter must be a string. The difference between the two "
"classes is that :exc:`BaseExceptionGroup` extends :exc:`BaseException` and "
"it can wrap any exception, while :exc:`ExceptionGroup` extends :exc:"
"`Exception` and it can only wrap subclasses of :exc:`Exception`. This design "
"is so that ``except Exception`` catches an :exc:`ExceptionGroup` but not :"
"exc:`BaseExceptionGroup`."
msgstr ""
"Ambos os tipos de exceção agrupam as exceções na sequência ``excs``. O "
"parâmetro ``msg`` deve ser uma string. A diferença entre as duas classes é "
"que :exc:`BaseExceptionGroup` estende :exc:`BaseException` e pode envolver "
"qualquer exceção, enquanto :exc:`ExceptionGroup` estende :exc:`Exception` e "
"só pode agrupar subclasses de :exc:`Exception`. Este design é para que "
"``except Exception`` capture um :exc:`ExceptionGroup` mas não :exc:"
"`BaseExceptionGroup`."

#: ../../library/exceptions.rst:922
msgid ""
"The :exc:`BaseExceptionGroup` constructor returns an :exc:`ExceptionGroup` "
"rather than a :exc:`BaseExceptionGroup` if all contained exceptions are :exc:"
"`Exception` instances, so it can be used to make the selection automatic. "
"The :exc:`ExceptionGroup` constructor, on the other hand, raises a :exc:"
"`TypeError` if any contained exception is not an :exc:`Exception` subclass."
msgstr ""
"O construtor de :exc:`BaseExceptionGroup` retorna uma :exc:`ExceptionGroup` "
"ao invés de uma :exc:`BaseExceptionGroup` se todas as exceções contidas "
"forem instâncias :exc:`Exception`, então ela pode ser usada para tornar a "
"seleção automática. O construtor de :exc:`ExceptionGroup`, por outro lado, "
"levanta :exc:`TypeError` se qualquer exceção contida não for uma subclasse "
"de :exc:`Exception`."

#: ../../library/exceptions.rst:931
msgid "The ``msg`` argument to the constructor. This is a read-only attribute."
msgstr ""
"O argumento ``msg`` para o construtor. Este é um atributo somente leitura."

#: ../../library/exceptions.rst:935
msgid ""
"A tuple of the exceptions in the ``excs`` sequence given to the constructor. "
"This is a read-only attribute."
msgstr ""
"Uma tupla de exceções na sequência ``excs`` dada ao construtor. Este é um "
"atributo somente leitura."

#: ../../library/exceptions.rst:940
msgid ""
"Returns an exception group that contains only the exceptions from the "
"current group that match *condition*, or ``None`` if the result is empty."
msgstr ""
"Retorna um grupo de exceções que contém apenas as exceções do grupo atual "
"que correspondem à condição *condition* ou ``None`` se o resultado estiver "
"vazio."

#: ../../library/exceptions.rst:943
msgid ""
"The condition can be either a function that accepts an exception and returns "
"true for those that should be in the subgroup, or it can be an exception "
"type or a tuple of exception types, which is used to check for a match using "
"the same check that is used in an ``except`` clause."
msgstr ""
"A condição pode ser uma função que aceita uma exceção e retorna verdadeiro "
"para aquelas que deveriam estar no subgrupo, ou pode ser um tipo de exceção "
"ou uma tupla de tipos de exceção, que é usada para verificar uma "
"correspondência usando a mesma verificação usada em uma cláusula ``except``."

#: ../../library/exceptions.rst:948
msgid ""
"The nesting structure of the current exception is preserved in the result, "
"as are the values of its :attr:`message`, :attr:`~BaseException."
"__traceback__`, :attr:`~BaseException.__cause__`, :attr:`~BaseException."
"__context__` and :attr:`~BaseException.__notes__` fields. Empty nested "
"groups are omitted from the result."
msgstr ""
"A estrutura de aninhamento da exceção atual é preservada no resultado, assim "
"como os valores de seus campos :attr:`message`, :attr:`~BaseException."
"__traceback__`, :attr:`~BaseException.__cause__`, :attr:`~BaseException."
"__context__` e :attr:`~BaseException.__notes__`. Grupos aninhados vazios são "
"omitidos do resultado."

#: ../../library/exceptions.rst:955
msgid ""
"The condition is checked for all exceptions in the nested exception group, "
"including the top-level and any nested exception groups. If the condition is "
"true for such an exception group, it is included in the result in full."
msgstr ""
"A condição é verificada para todas as exceções no grupo de exceções "
"aninhadas, incluindo o nível superior e quaisquer grupos de exceções "
"aninhadas. Se a condição for verdadeira para tal grupo de exceções, ela será "
"incluída no resultado por completo."

#: ../../library/exceptions.rst:961
msgid ""
"Like :meth:`subgroup`, but returns the pair ``(match, rest)`` where "
"``match`` is ``subgroup(condition)`` and ``rest`` is the remaining non-"
"matching part."
msgstr ""
"Como :meth:`subgroup`, mas retorna o par ``(match, rest)`` onde ``match`` é "
"``subgroup(condition)`` e ``rest`` é a parte restante não correspondente."

#: ../../library/exceptions.rst:967
msgid ""
"Returns an exception group with the same :attr:`message`, but which wraps "
"the exceptions in ``excs``."
msgstr ""
"Retorna um grupo de exceções com o mesmo :attr:`message`, mas que agrupa as "
"exceções em ``excs``."

#: ../../library/exceptions.rst:970
msgid ""
"This method is used by :meth:`subgroup` and :meth:`split`, which are used in "
"various contexts to break up an exception group. A subclass needs to "
"override it in order to make :meth:`subgroup` and :meth:`split` return "
"instances of the subclass rather than :exc:`ExceptionGroup`."
msgstr ""
"Este método é usado por :meth:`subgroup` e :meth:`split`, que são usados em "
"vários contextos para dividir um grupo de exceções. Uma subclasse precisa "
"substituí-la para fazer com que :meth:`subgroup` e :meth:`split` retorne "
"instâncias da subclasse em vez de :exc:`ExceptionGroup`."

#: ../../library/exceptions.rst:976
msgid ""
":meth:`subgroup` and :meth:`split` copy the :attr:`~BaseException."
"__traceback__`, :attr:`~BaseException.__cause__`, :attr:`~BaseException."
"__context__` and :attr:`~BaseException.__notes__` fields from the original "
"exception group to the one returned by :meth:`derive`, so these fields do "
"not need to be updated by :meth:`derive`."
msgstr ""
":meth:`subgroup` e :meth:`split` copiam os campos :attr:`~BaseException."
"__traceback__`, :attr:`~BaseException.__cause__`, :attr:`~BaseException."
"__context__` e :attr:`~BaseException.__notes__` do grupo de exceções "
"original para o retornado por :meth:`derive`, então esses campos não "
"precisam ser atualizados por :meth:`derive`. ::"

#: ../../library/exceptions.rst:983
msgid ""
">>> class MyGroup(ExceptionGroup):\n"
"...     def derive(self, excs):\n"
"...         return MyGroup(self.message, excs)\n"
"...\n"
">>> e = MyGroup(\"eg\", [ValueError(1), TypeError(2)])\n"
">>> e.add_note(\"a note\")\n"
">>> e.__context__ = Exception(\"context\")\n"
">>> e.__cause__ = Exception(\"cause\")\n"
">>> try:\n"
"...    raise e\n"
"... except Exception as e:\n"
"...    exc = e\n"
"...\n"
">>> match, rest = exc.split(ValueError)\n"
">>> exc, exc.__context__, exc.__cause__, exc.__notes__\n"
"(MyGroup('eg', [ValueError(1), TypeError(2)]), Exception('context'), "
"Exception('cause'), ['a note'])\n"
">>> match, match.__context__, match.__cause__, match.__notes__\n"
"(MyGroup('eg', [ValueError(1)]), Exception('context'), Exception('cause'), "
"['a note'])\n"
">>> rest, rest.__context__, rest.__cause__, rest.__notes__\n"
"(MyGroup('eg', [TypeError(2)]), Exception('context'), Exception('cause'), "
"['a note'])\n"
">>> exc.__traceback__ is match.__traceback__ is rest.__traceback__\n"
"True"
msgstr ""
">>> class MyGroup(ExceptionGroup):\n"
"...     def derive(self, excs):\n"
"...         return MyGroup(self.message, excs)\n"
"...\n"
">>> e = MyGroup(\"eg\", [ValueError(1), TypeError(2)])\n"
">>> e.add_note(\"a note\")\n"
">>> e.__context__ = Exception(\"context\")\n"
">>> e.__cause__ = Exception(\"cause\")\n"
">>> try:\n"
"...    raise e\n"
"... except Exception as e:\n"
"...    exc = e\n"
"...\n"
">>> match, rest = exc.split(ValueError)\n"
">>> exc, exc.__context__, exc.__cause__, exc.__notes__\n"
"(MyGroup('eg', [ValueError(1), TypeError(2)]), Exception('context'), "
"Exception('cause'), ['a note'])\n"
">>> match, match.__context__, match.__cause__, match.__notes__\n"
"(MyGroup('eg', [ValueError(1)]), Exception('context'), Exception('cause'), "
"['a note'])\n"
">>> rest, rest.__context__, rest.__cause__, rest.__notes__\n"
"(MyGroup('eg', [TypeError(2)]), Exception('context'), Exception('cause'), "
"['a note'])\n"
">>> exc.__traceback__ is match.__traceback__ is rest.__traceback__\n"
"True"

#: ../../library/exceptions.rst:1009
msgid ""
"Note that :exc:`BaseExceptionGroup` defines :meth:`~object.__new__`, so "
"subclasses that need a different constructor signature need to override that "
"rather than :meth:`~object.__init__`. For example, the following defines an "
"exception group subclass which accepts an exit_code and and constructs the "
"group's message from it. ::"
msgstr ""
"Observe que :exc:`BaseExceptionGroup` define :meth:`~object.__new__`, então "
"subclasses que precisam de uma assinatura de construtor diferente precisam "
"substituir isso ao invés de :meth:`~object.__init__`. Por exemplo, o "
"seguinte define uma subclasse de grupo de exceções que aceita um exit_code e "
"constrói a mensagem do grupo a partir dele. ::"

#: ../../library/exceptions.rst:1015
msgid ""
"class Errors(ExceptionGroup):\n"
"   def __new__(cls, errors, exit_code):\n"
"      self = super().__new__(Errors, f\"exit code: {exit_code}\", errors)\n"
"      self.exit_code = exit_code\n"
"      return self\n"
"\n"
"   def derive(self, excs):\n"
"      return Errors(excs, self.exit_code)"
msgstr ""
"class Errors(ExceptionGroup):\n"
"   def __new__(cls, errors, exit_code):\n"
"      self = super().__new__(Errors, f\"exit code: {exit_code}\", errors)\n"
"      self.exit_code = exit_code\n"
"      return self\n"
"\n"
"   def derive(self, excs):\n"
"      return Errors(excs, self.exit_code)"

#: ../../library/exceptions.rst:1024
msgid ""
"Like :exc:`ExceptionGroup`, any subclass of :exc:`BaseExceptionGroup` which "
"is also a subclass of :exc:`Exception` can only wrap instances of :exc:"
"`Exception`."
msgstr ""
"Como :exc:`ExceptionGroup`, qualquer subclasse de :exc:`BaseExceptionGroup` "
"que também é uma subclasse de :exc:`Exception` só pode agrupar instâncias "
"de :exc:`Exception`."

#: ../../library/exceptions.rst:1032
msgid "Exception hierarchy"
msgstr "Hierarquia das exceções"

#: ../../library/exceptions.rst:1034
msgid "The class hierarchy for built-in exceptions is:"
msgstr "A hierarquia de classes para exceções embutidas é:"

#: ../../library/exceptions.rst:1036
msgid ""
"BaseException\n"
" ├── BaseExceptionGroup\n"
" ├── GeneratorExit\n"
" ├── KeyboardInterrupt\n"
" ├── SystemExit\n"
" └── Exception\n"
"      ├── ArithmeticError\n"
"      │    ├── FloatingPointError\n"
"      │    ├── OverflowError\n"
"      │    └── ZeroDivisionError\n"
"      ├── AssertionError\n"
"      ├── AttributeError\n"
"      ├── BufferError\n"
"      ├── EOFError\n"
"      ├── ExceptionGroup [BaseExceptionGroup]\n"
"      ├── ImportError\n"
"      │    └── ModuleNotFoundError\n"
"      ├── LookupError\n"
"      │    ├── IndexError\n"
"      │    └── KeyError\n"
"      ├── MemoryError\n"
"      ├── NameError\n"
"      │    └── UnboundLocalError\n"
"      ├── OSError\n"
"      │    ├── BlockingIOError\n"
"      │    ├── ChildProcessError\n"
"      │    ├── ConnectionError\n"
"      │    │    ├── BrokenPipeError\n"
"      │    │    ├── ConnectionAbortedError\n"
"      │    │    ├── ConnectionRefusedError\n"
"      │    │    └── ConnectionResetError\n"
"      │    ├── FileExistsError\n"
"      │    ├── FileNotFoundError\n"
"      │    ├── InterruptedError\n"
"      │    ├── IsADirectoryError\n"
"      │    ├── NotADirectoryError\n"
"      │    ├── PermissionError\n"
"      │    ├── ProcessLookupError\n"
"      │    └── TimeoutError\n"
"      ├── ReferenceError\n"
"      ├── RuntimeError\n"
"      │    ├── NotImplementedError\n"
"      │    └── RecursionError\n"
"      ├── StopAsyncIteration\n"
"      ├── StopIteration\n"
"      ├── SyntaxError\n"
"      │    └── IndentationError\n"
"      │         └── TabError\n"
"      ├── SystemError\n"
"      ├── TypeError\n"
"      ├── ValueError\n"
"      │    └── UnicodeError\n"
"      │         ├── UnicodeDecodeError\n"
"      │         ├── UnicodeEncodeError\n"
"      │         └── UnicodeTranslateError\n"
"      └── Warning\n"
"           ├── BytesWarning\n"
"           ├── DeprecationWarning\n"
"           ├── EncodingWarning\n"
"           ├── FutureWarning\n"
"           ├── ImportWarning\n"
"           ├── PendingDeprecationWarning\n"
"           ├── ResourceWarning\n"
"           ├── RuntimeWarning\n"
"           ├── SyntaxWarning\n"
"           ├── UnicodeWarning\n"
"           └── UserWarning\n"
msgstr ""

#: ../../library/exceptions.rst:6 ../../library/exceptions.rst:17
#: ../../library/exceptions.rst:196
msgid "statement"
msgstr "instrução"

#: ../../library/exceptions.rst:6
msgid "try"
msgstr "try"

#: ../../library/exceptions.rst:6
msgid "except"
msgstr "except"

#: ../../library/exceptions.rst:17
msgid "raise"
msgstr "raise"

#: ../../library/exceptions.rst:41
msgid "exception"
msgstr "exceção"

#: ../../library/exceptions.rst:41
msgid "chaining"
msgstr "encadeamento"

#: ../../library/exceptions.rst:41
msgid "__cause__ (exception attribute)"
msgstr "__cause__ (atributo de exceção)"

#: ../../library/exceptions.rst:41
msgid "__context__ (exception attribute)"
msgstr "__context__ (atributo de exceção)"

#: ../../library/exceptions.rst:41
msgid "__suppress_context__ (exception attribute)"
msgstr "__suppress_context__ (atributo de exceção)"

#: ../../library/exceptions.rst:196
msgid "assert"
msgstr "assert"

#: ../../library/exceptions.rst:345
msgid "module"
msgstr "módulo"

#: ../../library/exceptions.rst:345
msgid "errno"
msgstr "errno"
